### ISSUE TITLE
[FEATURE] Integrate Plugwise-stick

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/plugwise-beta#116]
**Is your feature request related to a problem? Please describe.**
HA Core team requests single brand integrations (https://github.com/home-assistant/core/pull/35713)

**Describe the solution you'd like**
Create a user testable integrated `custom_component` capable of discoverying and handling both USB and Network components

**Describe alternatives you've considered**
n/a

**Home Assistant (please complete the following information):**
 - Version: 0.115.x onward
 - Deployment: n/a
 - Installed plugwise version: plugwise-beta
 - Installed through starting with HACS/custom_component leading back into above mentioned PR

**Smile (please complete the following information):**
 - Sort of Smile: USB (stealth/circle0
 - Firmware: n/a
 - Setup: USB-discovery and manual - retaining functionality for both USB and networked setups

**Additional context**
See mentioned PR

**Comment by CoMPaTech** [comment]
While getting together for discord, an incomplete list of 'things to tick'?

 - [ ] Is there USB discovery? (And is it even a thing?)

 - [ ] Clean up applicable 'network' (stretch/smile) parts of __init__.py to `gateway.py` (naming suggestion good?)
 - [ ] Convert applicable 'usb' parts of 35713 and/or custom_component of brefra to `usb.py` (naming suggestion ok?)

 - [ ] (more to come) `__init__.py`
    - [ ] Introduce `hass.data[DOMAIN][config_entry.entry_id]["pw_type"]` indicating `gw` or `usb` (hinting towards the `...["api"] and `...["stick"]` settings that can continue to be there simplifying integration?

 - [ ] `config_flow.py` things
    - [ ] Check what to do with `_base_schema` (originating from gw) - usb has this included in the form-steps
    - [ ] Rename `validate_input` to gw (same with `validate_connection` from usb)
    - [ ] Check how to handle `async_get_options_flow` from gw wrt usb options (for now `scan_interval` with gw, but maybe more in the future or from usb side)
    - [ ] Cook up new user steps for `config_flow.py`
       - [ ] USB `async_step_user|async_show_form| async_step_manual_path` postfix with `_usb` => `async_step_user_usb` etc.
       - [ ] Gateway `async_step_user| async_step_zeroconf |` postfix with `_gw` => `async_step_user_gw`
       - [ ] Make (if existing) USB-discovery point it's own counterpart
       - [ ] Make GW-discovery point to it's own counterpart
       - [ ] Create new `async_step_user` pointing to either `async_step_user_usb` of `async_step_user_gw` after selecting "USB or Networked device" (see example below)

 - [ ] Rework `switch.py`
    - [ ] Switch between usb/gw, probably rewriting `async_setup_entry` to use `hass.data[DOMAIN][config_entry.entry_id]["pw_type"]` to switch between mode
    - [ ] As for the `PlugwiseSwitch/PwSwitch` entities, we need to address calling the right module as we use different ways to 'toggle' switches (for one). i.e. async `self._api.set_relay_state(self._dev_id, "on"):` vs sync `getattr(self._node, self.switch_type["switch"])(True)`

Example code part of new `async_step_user` without input (i.e. when **not** `if user_input is not None:`). We can leave the `......` part either empty (but the user might not notice there must be a selection, though after trying to click submit that will be clear) or we suggest either USB or Network.

```
    async def async_step_user(self, user_input=None):
        return self.async_show_form(
            step_id="init",
            data_schema=vol.Schema(
                {
                    vol.Required("id", default="......"): vol.In(
                        {
                            "select_usb": "Configure a USB stealth/circle",
                            "select_gw": "Configure a Smile or Stretch",
                        }
```

<img width="397" alt="Schermafbeelding_2020-09-21_om_13 16 48" src="https://user-images.githubusercontent.com/5751088/93810767-6710ed80-fc4f-11ea-8fd3-58c353518584.png">
<img width="414" alt="Schermafbeelding 2020-09-21 om 16 48 30" src="https://user-images.githubusercontent.com/5751088/93810816-78f29080-fc4f-11ea-8f2d-0ad18f749573.png">

**Comment by brefra** [comment]
@CoMPaTech, great start already !
A quick reply about the USB-detection: I did some research in the past and could not find anything usefull to detect the plugwise stick. This is because its based on the famous FTDI chip. So there is no way to distinguish between a normal USB to serial adapter (which could have internally a FTDI chip too) and a Plugwise USB-stick as both have the same hardware id's.

**Comment by CoMPaTech** [comment]
Ah, FTDI ... the fond memories (not) :) So config flow is either discovery (networked) or manual with a first step of 'USB or Network'. Adjusting the above!

**Comment by CoMPaTech** [comment]
Updated the checklist as per #117 progress - I didn't take `"pw_type"` into account yet, but we'll need this once we hit the platforms. For now #117 is working 'on my laptop' wrt both discovered and manual adding for network. With USB I do get upto `(entry.data[CONF_USB_PATH]) -> KeyError: 'usb_path'` though without filling anything in.

**Comment by CoMPaTech** [comment]
Updated the check-/todolist - switch is intercopied (was going to say integrated, but looking at the code I doubt we can effortlessly deduplicate id), but having no plugs nor circle's unable to test, up to you guys.

**Comment by CoMPaTech** [comment]
Also seeing #122 (tnx @bouwew) I vote against the idea of `PW_TYPE` and we should just replace this by looking of `CONF_HOST` or `CONF_USB_PATH` are present. Or better yet ... test for lack of `CONF_HOST` (ie order of business will be assume network unless).
Up for debate, with network working properly and discoverable. Should we favor 'USB' in the first step? I.e. as network user will probably always use discovery unless their device isn't local in which case they fall into 'advanced category' anyway?
