### ISSUE TITLE
Entity is not available because of the date/time error

### ISSUE THREAD

**Issue by alex-mikhaylov** [plugwise/plugwise-beta#127]
Hello,

First of all, thanks a lot for all your hard work and support!

Two days ago I bought and installed an Anna thermostat with the smile gateway and managed to use your plugin without any issues until yesterday I change the schedule from the Plugwise app. I believe that setting an event to 00:15 causes an issue in Home Assistant and makes the thermostat not available.

Here's the error that I see in the logs:
```
Logger: homeassistant.components.climate
Source: custom_components/plugwise/climate.py:252
Integration: Climate (documentation, issues)
First occurred: 23:45:45 (2 occurrences)
Last logged: 23:47:21

Error while setting up plugwise platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/plugwise/gateway.py", line 247, in async_added_to_hass
    self._async_process_data()
  File "/config/custom_components/plugwise/climate.py", line 252, in _async_process_data
    climate_data = self._api.get_device_data(self._dev_id)
  File "/usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py", line 790, in get_device_data
    avail_schemas, sel_schema, sched_setpoint = self.get_schemas(
  File "/usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py", line 1112, in get_schemas
    start = dt.datetime.strptime(moment_1[1], "%H:%M").time()
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '24:15' does not match format '%H:%M'
```

I can work this around by changing the schedule event time to for example 23.45.

Happy to share more details if needed.

**Comment by CoMPaTech** [comment]
Hi Alex, we'd be happy to take a look at that ... `24:15` is a great clue, let's see how it got there. We might be able to test ourselves as well, but if you are able to provide see below. Turning in for the night now though :)

Before sending in a full `domain_objects` could you have a look at `http://{your-ip}/core/domain_objects` and search for `zone_preset_based_on_time_and_presence_with_override`? There might be a few, just look for your schema-name and something that resembles the screenshot attached. If you can share that (either by screenshot or that part of the XML-data) we can see how plugwise offers `24` instead of `00` and take appropriate counter-measures!

![Schermafbeelding 2020-10-16 om 00 01 30](https://user-images.githubusercontent.com/5751088/96190810-1c7b4c00-0f43-11eb-9579-3ff284553cc9.png)

**Comment by bouwew** [comment]
@alex-mikhaylov what is the firmware-version of your Anna?

**Comment by alex-mikhaylov** [comment]
Hi @CoMPaTech and @bouwew, thanks for getting back to me. 

I had a look at `http://{your-ip}/core/domain_objects` and found out that my schedule was kind of corrupted - instead of changing twice day as shown in the Plugwise app, some time periods were several days long (e.g. Monday - Wednesday). I re-did the schedule from scratch, and the issue with `ValueError: time data '24:15' does not match format '%H:%M'` is gone. I think the Plugwise app is to blame, as it did something wrong to the schedule.

Here's how the new schedule looks like:

![image](https://user-images.githubusercontent.com/21146073/96269240-65c2ae80-0fca-11eb-8dcf-52114eae8f3e.png)

If I'm not mistaken the firmware version is `2018-02-08T11:15:53+01:00` and the software version is `4.0.20`.

I will keep checking logs from time to time and will let you know if it happens again. Thank you for your help!

**Comment by alex-mikhaylov** [comment]
After running a new schedule for several days, I can confirm that the issue is not there, so it was indeed a Plugwise app issue. Thanks a lot for your help and sorry for a false alarm
