### ISSUE TITLE
[BUG] Can't install Plugwise custom component because of HACS version check of HA 

### ISSUE THREAD

**Issue by bhavers** [plugwise/plugwise-beta#137]
**Describe the bug**
Can't install Plugwise Beta 0.12.2 component through HACS.
I have installed HA version 0.117.0b5 and added the custom repo to HACS 1.6.0.

**Evidence**
In HACS (after selecting Integration --> Plugwise Beta custom component --> Install) i get the following error message: You are running Home Assistant version '0.117.0b5', but this repository requires minimum version '0.117.0' to be installed.
Could there be something wrong with the version check by HACS?

**Comment by CoMPaTech** [comment]
Hi @bhavers, sorry, we didn't get around to fix that yesterday, the problem is that `0.117.0` > `0.117.0.bX`. So a release is always higher than beta's. We'll have a look this morning, apologies for the inconvenience!

**Comment by CoMPaTech** [comment]
`0.12.3` should appear if all went well

**Comment by bhavers** [comment]
@CoMPaTech great work! It was about 01.00 in the evening for me so had to go to bed to anyway ;-)
I can confirm that it works now. Thx for the fast response and fix.

**Comment by CoMPaTech** [comment]
NP, thanks for reporting!
