### ISSUE TITLE
[TODO] Cyclic import

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/plugwise-beta#138]
**Todo**
Codefactor reports a cyclic import in plugwise/usb.py: we do `import plugwise` thus potentially importing itself :) Nothing Python won't resolve itself but I would suggest we squash this before upstreaming.

**Comment by bouwew** [comment]
This has been solved in beta v0.14.0?

**Comment by CoMPaTech** [comment]
Yup, we really should link issues and PRs :)
