### ISSUE TITLE
[FEATURE] Add P1 Usage Today and Cost Today as sensors

### ISSUE THREAD

**Issue by Veldkornet** [plugwise/plugwise-beta#143]
**Is your feature request related to a problem? Please describe.**
Have the daily costs and usage added as sensors. The costs are already shown on the Plugwise P1 itself, so I assume these are things which can be added? 

**Describe the solution you'd like**
Practically, the information shown on the Plugwise itself in terms of usage and costs I’d like to see in HomeAssistant.
As an example, the Toon integration shows the costs/usage per type for the day and this is sufficient.
- Energy Usage Today (kWh)
- Gas Usage Today (M3)
- Energy Cost Today (EUR)
- Gas Cost Today (EUR)

**Describe alternatives you've considered**
Not clear if there are alternatives here

**Home Assistant (please complete the following information):**
 - Version: '0.118.3'
 - Deployment: 'intel-nuc/hassio'
 - Installed plugwise version: 'plugwise-beta'
 - Installed through 'HACS'

**Smile (please complete the following information):**
 - Sort of Smile: P1
 - Firmware: 4.0.7
 - Setup: Just the P1 connected to a smart meter

**Additional context**
I’m attempting to replace my Toon with Plugwise, but of course, I’d like to still have the same functionality available in HomeAssistant. The screenshot below is from the Plugwise app itself, I’d just like to see this now in HomeAssistant.

![8C884208-B21B-4644-82E5-1F5D876E9344](https://user-images.githubusercontent.com/10297361/100241398-efec2400-2f33-11eb-9a13-283320966f64.jpeg)

**Comment by Veldkornet** [comment]
I seemed to be able to calculate the usages with [Utility Meter](https://www.home-assistant.io/integrations/utility_meter/) as suggested in the other issue, just need to figure out the costs now...

**Comment by bouwew** [comment]
Decision: this feature will not be implemented. We suggest using the `Utility_Meter` or 'Integration' integration.
