### ISSUE TITLE
The auxillairy modulation level % is not correct. 

### ISSUE THREAD

**Issue by djveldm** [plugwise/plugwise-beta#154]
![firefox_2021-02-16_09-33-31](https://user-images.githubusercontent.com/63648032/108038208-dcd08800-703a-11eb-9d0a-335b672e9f6e.jpg)

As you can see this graph is not realistic: The heater is burning in the time the value indicated is zero.
It is an important value to understand the malfunction the Plugwise Adam.
The zero is not zero: an offset problem?

**Comment by bouwew** [comment]
You should also show the `flame-state` in the history-graph, heating does not necessarily mean that the flame is on, it means that hot water is being circulated, only when needed the flame is turned on.

The zero not being zero, what is the modulation measurement-value at that these moments? When hoovering over the graph with you mouse-pointer it should show a value, hoover at the point where the value changes.

**Comment by bouwew** [comment]
About the %-value, we do `int(float(value)*100)` so if the %-value is not 0 the raw value must be also be not 0.

**Comment by bouwew** [comment]
After a more detailed look at the modulation-graph, it shows zero when the flame is off.
So, what do you mean by "zero is not zero"?

**Comment by djveldm** [comment]
Tx for reply!
See the new picture. The flame state is the second purple line line: Heating, Aux..
In that line is a blue part: the time the heating is idle: no flame.
In the graph you see there is no match and also, when the graph is 0, the heating at the heater is burning in real life.
In the graph: the greene line drops at a moment: then the heater stops: idle.
Note that the time lines are different projected: see 11:00 hrs.
![firefox_2021-02-16_11-36-36](https://user-images.githubusercontent.com/63648032/108052290-31c8ca00-704c-11eb-9e3c-add62fb0fb5f.jpg)

**Comment by bouwew** [comment]
You misunderstand, there is a separate binary sensor that shows the flame-state: `binary_sensor.auxiliary_flame_state`.
Again, `heating_state` is not the same as `flame_state`, I know this from my own heating system. 
I explained this in my 1st response, was that not clear?

**Comment by djveldm** [comment]
![firefox_2021-02-16_12-24-28](https://user-images.githubusercontent.com/63648032/108056849-195bae00-7052-11eb-81ea-d38dfd2f2a01.jpg)
I am sorry: this is what I can choose. I have no binary sensor flame. I am using not the beta but Plugwise via the core.
I still think that "Auxiliary device state" is the flame or activity of heating.

**Comment by bouwew** [comment]
Ah yes, correct, the `flame_state` has not been added to Plugwise Core yet. You should switch to Plugwise-beta ;)

Take it from me, heating_state does not show when the flame is on, it shows when the heat is being distributed, only now and then the flame comes on when the water temperature has dropped below the intended water temperature.

**Comment by djveldm** [comment]
Anyway, I keep having a problem with the modulation zero...
I think over the switching to beta.

Is English or Dutch the language at Github?
Greetings, Dirk

**Comment by djveldm** [comment]
Bouwe, It is not the problem of your integration: in the app from Plugwise the modulation is projected this way: they sent hte wrong information! The graph should be continued below zero ;-). Important information is not visible and the Pluwise integration receives bugged info. What next?
![firefox_2021-02-16_13-45-41](https://user-images.githubusercontent.com/63648032/108064786-727d0f00-705d-11eb-9fa8-d6aa3e6029f6.jpg)

**Comment by bouwew** [comment]
Yes, switching to plugwise-beta is a good idea. And then add the `flame_state` binary_sensor, with that added the graphs will make more sense, I promise you.

The information that Plugwise provides in their graphs is correct, you just don't fully understand what is shown in the data :)
Also, I noticed that the red bar = heating_state is lagging behind in the graph: look tomorrow again at this picture, then the missing part of the red bar will be there. You might call that a bug: the red bar is not shown until the heating has stopped for a short while. You see the orange vertical line after the first red bar, that means that at that moment the "next" heating period has started but because this period has not yet ended, the "next" red bar is not shown.

Don't worry about the Plugwise integration receiving bugged info, I might be wrong but I don't have that impression. I have looked at the data of my system every day over the last 6 months. I never found anything to be out-of-order.

**Comment by djveldm** [comment]
Inderdaad, ik kreeg net commentaar terug van Plugwise met deze grafiek van gisteren.
Dus flame zal echt iets anders zijn als de state. En de grafiek 0 klopt. Sorry sorry voor de verwarring.

Van deze grafiek wordt ik niet blij. Er wordt louter gestuurd op watertemperatuur: de ketel gaat daar helemaal op los.
Ze werken eraan, dus wie weet..

Dank in ieder geval! Dirk.
![e4RfAa43exivF4DC8MrVuHhmxmjBxuDYQw](https://user-images.githubusercontent.com/63648032/108078685-43bb6480-706e-11eb-9bee-b29cc9542f86.png)

**Comment by bouwew** [comment]
Geen probleem hoor, een verwarmingsalgoritme is best wel complex, veel variablelen zoals je kunt zien.

Dus, geen bug is de conclusie? Zou je dan deze Issue willen sluiten?

**Comment by djveldm** [comment]
Geen bug maar een gruwelijke grafiek ;-). Tx!!
