### ISSUE TITLE
[BUG] Can't get component activated for usb stick in python 3.9.1

### ISSUE THREAD

**Issue by aerrow5** [plugwise/plugwise-beta#168]
**Describe the bug**
USB stick cant be activated due to unknown error.
Logging shows: 
   AttributeError: 'Thread' object has no attribute 'isAlive'

Changed 'isAlive' into 'is_alive' in source code stick.py + __init__.py solved the issue.
Seems that 3.9 doesn't support isAlive() anymore (https://bugs.python.org/issue37804)

**Comment by bouwew** [comment]
Thanks for letting us know!

Which version of the Plugwise (beta) integration are you using?

**Comment by aerrow5** [comment]
I used plugwise-beta downloaded yesterday: v0.9.4a9.

**Comment by bouwew** [comment]
Fixed in v0.14.6
