### ISSUE TITLE
[BUG] Unable to serialize to JSON. Bad data found ... power_w=nan ...

### ISSUE THREAD

**Issue by wfroemgen** [plugwise/plugwise-beta#179]
**Describe the bug**
HA is unresponisve when accessing History, or from time to time without noteable cause.

**Evidence**
From Log:
```
2021-06-26 10:31:44 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.result[293](State: switch.relay_state_38b3f).attributes.current_power_w=nan(<class 'float'>
```

``` 
# Add/modify configuration.yaml
logger:
  default: warn
  logs:
    custom_components.plugwise-beta: debug
```
Done, but somehow cant get additional info as described

**Expected behavior**
HA should not crash and should show the current Power for all devices

**Screenshots**

**Home Assistant (please complete the following information):**
 - Virtual Maschine on Synology NAS
 - Host: Home Assistant OS 6.1
 - core: 2021.6.6
 - supervisor: 2021.06.6
 - Update-Channel: beta
 - Installed plugwise version: Plugwise beta custom component 0.16.0
 - Installed through: HACS

**Plugwise-Setup:**
 - USB-Stick
 - Circle+: 1x type F, Firmware: 2015-09-18 10:53:15
 - Circle: 20x type F, Firmware: 2015-09-18 10:53:15
No Updates found with source 2.40 (20180404.555)

**Additional context**

**Comment by bouwew** [comment]
Not plugwise related? The header shows `homeassistant.components.websocket_api.messages`.
This points to the home assistant websocket_api component.

**Comment by bouwew** [comment]
This HA Core issue shows a similar message in the last post: https://github.com/home-assistant/core/issues/50905
Please add your findings to this issue.

**Comment by bouwew** [comment]
Not a plugwise-related issue.
