### ISSUE TITLE
Gas usage not updated [BUG]

### ISSUE THREAD

**Issue by malosaa** [plugwise/plugwise-beta#187]
Gas usage not working correctly,
I did double-check the smile p1, as i have a plugin on HomeSeer that reports the live gas usage of the p1 
it receives it correct.

But here in HASS it's a different thing,
Right now the gas should update, but it did not update, when I check the history tab of this device : 
P1 Gas Consumed Cumulative - sensor.p1_gas_consumed_cumulative
it shows up like this: 3.476,877 m³ (that's the total) but on HomeSeer it's 3.502.008
even in the history tab of HASS device it sometimes shows a minus value like: cumulative:  -11020

I did restart a couple of times, but nothing changes, the value stays the same

Any idea what's wrong?

On HASS
![image](https://user-images.githubusercontent.com/13116501/127653708-1461c0b8-e56d-4639-913f-123fcb692e67.png)

on HomeSeer

![image](https://user-images.githubusercontent.com/13116501/127653570-ca4736e1-7f59-43e2-b363-f18fba3fff2b.png)

Regards 

**Home Assistant (please complete the following information):**
 - Version: core-2021.7.4
 - Deployment: Windows (virtual box)
 - Installed plugwise version: [last beta]
 - Installed through [HACS]

**Smile (please complete the following information):**
 - Smile P1 
 - Firmware: 2.1.13

**Comment by bouwew** [comment]
Please provide more information, as requested in the bug-report template.

**Comment by malosaa** [comment]
Well thanks for the reply, 

There is not even 1 message of that device in the log.
i checked back for 1 week.

it does not update at all, it says last changed yesterday morning when i restarted HASS.
All the other devices are working correct.

regards

**Comment by bouwew** [comment]
Please kindly answer my first question.

**Comment by malosaa** [comment]
I did add the code to my yaml, the log section in developer-tools --> logs not showing up..

**Comment by bouwew** [comment]
Thanks for adding the info. This helps narrowing down where the bug could be in the code.
It's likely present in the backend-library plugwise.

Strange that you are not seeing any plugwise-beta debug messages. Are you looking in the correct "place" ?
You need to look at Configuration --> Logs --> LOAD FULL HA LOG.

**Comment by bouwew** [comment]
After a quick check, looks like you have a legacy P1 with a firmware that is very old.
We have decided to not include support for this version of the firmware because we would need to rewrite a lot of code.

I would suggest you use this: https://bitbucket.org/jvdschoot/home-assistant-sensor-plugwise-smile-p1/src/master/plugwisesmile.py and create a custom_component using this code.

Put the above code in the files `__init__.py` and add a simple `manifest,json` file in the same directory, see here for what needs to be inside the file: https://developers.home-assistant.io/docs/creating_integration_manifest/

**Comment by bouwew** [comment]
See also https://bitbucket.org/jvdschoot/home-assistant-sensor-plugwise-smile-p1/src/master/README.md on how to use the custom_component in HA Core. To make this work you need to create a directory: `custom_components/plugwisesmile/`

About creating a custom_component, see here: https://aarongodfrey.dev/home%20automation/building_a_home_assistant_custom_component_part_1/

**Comment by bouwew** [comment]
On a 2nd thought, we could include this code in our github, as a separate custom_component. I can quickly create a new sub-repository. Then you can easily include it via HACS. Would you prefer that?

**Comment by bouwew** [comment]
Ok done, please see https://github.com/plugwise/p1_legacy

Please try installing via HACS. Let me know when something is not working.

**Comment by malosaa** [comment]
Many thanks for all the help. 
I will look into it,

Yes the logs don't show up, i did also try for another component and that one works.

**Comment by malosaa** [comment]
Well I did install everything, I did restart.
But there is one thing, I get this error: 

```
Configuration invalid

Platform error sensor.plugwise_p1_legacy - No module named 'custom_components.plugwise_p1_legacy.sensor'
```

**Comment by bouwew** [comment]
There should also be a message with more information in the FULL HOME ASSISTANT LOG, can you please have a look?

**Comment by bouwew** [comment]
I've made some changes, please update to v0.0.2. Does this help?

**Comment by malosaa** [comment]
I did double check the log, nothing in there, i did expand to check the full log.

getthing this now 


Invalid config for [sensor.plugwise_p1_legacy]: [name] is an invalid option for [sensor.plugwise_p1_legacy]. Check: sensor.plugwise_p1_legacy->name. (See ?, line ?).

**Comment by bouwew** [comment]
Thanks, let me check the code...

**Comment by malosaa** [comment]
You're welcome
Well obviously without name I can't find it.

**Comment by bouwew** [comment]
I think it should be something like this:
`    name: "Plugwise P1-legacy"`
The " " are required. But you can leave the name-line out as well.

Can you please try with the ""'s? What are the names of the sensors with the name-line?
Also can you try without the name-line? What are the names of the sensors then?

**Comment by malosaa** [comment]
Well i did try without name, i don't find the sensors.
And like this name: "Plugwise P1-legacy" still the same error

**Comment by malosaa** [comment]
this is in my yaml under sensors

```
### LEGACY GAS P1
  - platform: plugwise_p1_legacy
    name: "Plugwise P1-legacy"
    host: 192.168.1.13
    username: smile
    password: wpjkbckk
    resources:
      - gas_consumed_interval
      - gas_consumed_cumulative
```

**Comment by bouwew** [comment]
After double-checking: remove the name-line, I'm sure now that this line is not needed.

**Comment by bouwew** [comment]
I've just realized that I have done this work before, here: https://github.com/bouwew/smilep1
And that was working some time ago, almost one year ago.

**Comment by bouwew** [comment]
I think I have copied over all the changes but I forgot about removing the name-line.

**Comment by malosaa** [comment]
ok lets update and check again without name line

**Comment by malosaa** [comment]
i checked. cant find the legacy devices.
I only find the 2 devices from the beta plugin.

**Comment by bouwew** [comment]
You only need to update your yaml-code and then restart HA Core.
The password is the 8-letter Smile ID.

**Comment by bouwew** [comment]
You need to remove the plugwise-beta integration, both will create the same sensors I would guess.

**Comment by bouwew** [comment]
And look for "gas_consumed_cumulative" not for "p1_legacy".

**Comment by malosaa** [comment]
Yes i did, i get only the old ones, right now i disabled the 2 old ones, see what happens now

**Comment by bouwew** [comment]
Maybe the last sensor is called "cumulative_consumed_gas".

**Comment by malosaa** [comment]
thats it, i find it.

**Comment by malosaa** [comment]
PSP1 Cumulative Consumed Gas is the device

**Comment by bouwew** [comment]
Good news!

Why do you only use the gas-sensors and not the electricity-sensors?

**Comment by malosaa** [comment]
the electricity sensors still working with your beta version, and the gas is now working with this version

**Comment by bouwew** [comment]
I strongly advise you to use the P1-legacy component also for the electricity-sensors. If you want I can change the names of the electricity sensors. That is probably clever to do anyway. But that will have to wait till tomorrow.

**Comment by malosaa** [comment]
No worries, take your time, i can also change the sensor.py file locally.
I'm already really happy u did quick fix this issue.

Thanks for everything and your time !!

**Comment by bouwew** [comment]
You're welcome :)

**Comment by bouwew** [comment]
@malosaa I have released version 0.1.0b0: the `p1-legacy` custom_component now should show the same sensors as plugwise-beta.
Please test and let me know if all is OK.

**Comment by malosaa** [comment]
Ok, many thanks, I will test when I'm back.


I did quickly check the code:
I  see 2 device names are incorrect, it must be: Produced_Peak_point end Consumed_Peak_Point

I'm still running both, the beta and this one, i only disabled the 2 gas devices and use these.
What i going to do when i'm home is test this version on a new system and check if it all works.

**Comment by bouwew** [comment]
I've added both point-sensors, please try v0.1.0b1.

**Comment by malosaa** [comment]
Thanks, i will once I'm heading home. 
i let u know asap.

**Comment by bouwew** [comment]
Please note the resources update:
```
    resources:
      - electricity_consumed_point
      - electricity_consumed_offpeak_interval
      - electricity_consumed_peak_interval
      - electricity_consumed_offpeak_cumulative
      - electricity_consumed_peak_cumulative
      - electricity_produced_point
      - electricity_produced_offpeak_interval
      - electricity_produced_peak_interval
      - electricity_produced_offpeak_cumulative
      - electricity_produced_peak_cumulative
      - net_electricity_point
      - net_electricity_cumulative
      - gas_consumed_interval
      - gas_consumed_cumulative
```

The two net_electricity sensor that are in `plugwise-beta` were added.

**Comment by malosaa** [comment]
Thanks again, sorry for the late reply
like i can see it's working. 

i will test some more when i have more time, 

many thanks for updating and fixing!
regards

**Comment by bouwew** [comment]
No problem, I happy I'm able to help.

I have some other updates in the github develop-branch that I haven't put into a release yet. I'll wait with that until you find that the p1-legacy integration works better than plugwise-beta.

I really wonder if it works better because my experience with a P1 with that firmware is that it's quite buggy. I've seen the electricity values regularly drop to 0 for several minutes, several times per day. I'm not sure if this was related to the code of the integration, or not.

Please test with the present version of p1-legacy and let me know if it works well, or not.

**Comment by bouwew** [comment]
@malosaa Please test plugwise-beta v0.17.5b0, this new version now also supports your (and mine :) ) P1. You don't need to use the P1-legacy component any more. 

The process to follow:
- Update plugwise-beta via HACS (via show beta)
- Uninstall the P1-legacy via HACS
- Remove the P1-legacy yaml-configuration
- Restart HA Core
- Add the P1 into plugwise-beta, either via discovery or manually.

Please note, the `electricity_consumed_point` and `electricity_produced_point` sensors will be named `electricity_consumed_peak_point` and `electricity_produced_peak_point`. This is how it was implemented by my fellow-code-owner in the past.

Also, the default scan-interval is 10 seconds, with that number I'm seeing several connection errors in Logs so I've set the interval to 20 seconds via CONFIGURE.

**Comment by malosaa** [comment]
@bouwew 

i will try after this weekend.
thanks for the support, i report back when tested :)

**Comment by malosaa** [comment]
@bouwew 

gas not working 
shows still this static value: 3476.877

needs to be: 3524.090 m3

**Comment by malosaa** [comment]
the weird thing is that the value what is received from your script is not in here.
do you get the devices from smileIP/core/modules ?  


```
<services>
<gas_interval_meter id="3cc5cd03a0e9434385e77df40e422912">
<measurement log_date="2021-08-22T12:00:00+02:00" unit="m3" interval="PT1H" directionality="consumed">0.000</measurement>
</gas_interval_meter>
<gas_cumulative_meter id="4f02911f5e58474190403341832a7719">
<measurement log_date="2021-08-22T12:30:00+02:00" unit="m3" directionality="consumed">3524.090</measurement>
</gas_cumulative_meter>
```

**Comment by malosaa** [comment]
i see where the value is coming from
/core/direct_objects

it retrieves the wrong value 

look here:
```

<cumulative_log id="ec4199cd41714dbfa0bc74fcf39aff0a">
<unit>m3</unit>
<type>gas_consumed</type>
<last_consecutive_log_date>2021-07-02T11:30:00+02:00</last_consecutive_log_date>
<updated_date>2021-07-02T11:30:00+02:00</updated_date>
<period start_date="2019-07-15T15:00:00+02:00" end_date="2021-07-02T11:30:00+02:00">
<measurement log_date="2021-07-02T11:30:00+02:00">3476.877</measurement>
</period>
</cumulative_log>
```

**Comment by malosaa** [comment]
Better don't use /core/direct_objects

Use  core/domain_objects   instead.

it contains 2x gas value. 

The good one:
```
<services>
<gas_interval_meter id="3cc5xxxxxxxx77df40e422912">
<measurement log_date="2021-08-22T12:00:00+02:00" unit="m3" interval="PT1H" directionality="consumed">0.000</measurement>
</gas_interval_meter>
<gas_cumulative_meter id="4f02911xxxxxxxxxxxxx1832a7719">
<measurement log_date="2021-08-22T12:40:00+02:00" unit="m3" directionality="consumed">3524.090</measurement>
</gas_cumulative_meter>
</services>
```

and the bad one:

```
<cumulative_log id="ec4199cd41714dbfa0bc74fcf39aff0a">
<unit>m3</unit>
<type>gas_consumed</type>
<last_consecutive_log_date>2021-07-02T11:30:00+02:00</last_consecutive_log_date>
<updated_date>2021-07-02T11:30:00+02:00</updated_date>
<period start_date="2019-07-15T15:00:00+02:00" end_date="2021-07-02T11:30:00+02:00">
<measurement log_date="2021-07-02T11:30:00+02:00">3476.877</measurement>
</period>
</cumulative_log>
```

**Comment by bouwew** [comment]
@malosaa which plugwise-beta version are you using? Should be v0.17.5b3.

In that version the data is obtained from /core/locations.
In P1 legacy the data is taken from /core/modules. On my P1 the data in /core/locations is the same as in /core/modules

**Comment by bouwew** [comment]
@malosaa Never mind, fixing the issue as I am writing this. I will create a new pw-beta version for you to test.

**Comment by bouwew** [comment]
Please test pw-beta v0.17.5b4, this version should show the correct `gas_consumed_cumulative` measurement.

**Comment by malosaa** [comment]
@bouwew 

i will test, but i have an issue, right when i wanted to restart homeassistant os it corrupted my vdi file, i cant start homeassistant... 
so i need to find a way to open the vdi file and get my last backup.. i did make one but forget to save on my other pc... 

regards

**Comment by malosaa** [comment]
i will recreate the system soon, my hdd has a smart error and the bad thing is that my vdi file has the bad cluster in the data folder.. i can't recover, so lost 10 days of configs and settings.. 

ill let u know when i did test it, waiting for my new hdd..

**Comment by malosaa** [comment]
@bouwew 

i'm back, my whole server was fried.
Needed to do a lot of stuff..
So i had only a backup from 10 august... damn.

But i did update the plugwise p1 beta, and still gas usage is not working. getting that weird 3.476.877 value
