### ISSUE TITLE
[FEATURE] add more sensors for plugwise adam

### ISSUE THREAD

**Issue by malosaa** [plugwise/plugwise-beta#193]
Would like if its possible and not take a lot of time to add some more sensors of plugwise adam.
I'm currently thinking of switching fully to homeassistant, but i'm missing some devices.

see my 2 screenshots, that are the devices created from retrieving the xml from adam by my plug-in.
Thats on homeSeer.
Using last version ofn adam

as u can see i can control some of the adam devices on homeseer that i regulary use.

like i'm missing the control of :
- hot domestic water comfort mode
- regulation state 
- max boiler temp
- hot water setpoint

![image](https://user-images.githubusercontent.com/13116501/129381991-bfbfda4c-16c4-4530-9ea1-9bfbeae55fb9.png)

![image](https://user-images.githubusercontent.com/13116501/129381912-5af2751f-f837-433e-8df4-557fdd6f1d2c.png)

if its not possible to integrate, no problem, just a question:)

regards and many thanks for this awsome support and work you guys do !!

**Comment by bouwew** [comment]
The comfort mode is a switch, it should be there:
![image](https://user-images.githubusercontent.com/11290930/129385761-50e4fa01-6ba7-4b6b-887e-7bdd5463cbab.png)
If not, check the disabled entities.

**Comment by bouwew** [comment]
What is the purpose of the other 3? And how often do you change these?

Which ones is a must-have and which ones you can live without? I'm asking this because it will take a lot of effort to implement these features.

**Comment by malosaa** [comment]
no worries, if it takes to much to make it its no problem at all.

- regulation state puts my heater in 3 modes, 1 to bleeding hot causing it to super heat. 2 bleeding cold to cool down. 3 to off 
- domestic hotwater setpoint is needed, because if u go on vacation or whatever u can change it to lower so it doesnt consume much, aswell if its winter and freezing u can set it higher to 80c so the water is directly hot, without using the thermostat.
- boiler temperature, same as above.

but u don't have to implement it, if its really a lot of work than better don;t do it, as not much people gonna use it anyways
i'm still using homeseer to automate the adam and anna.

regards and many thanks
