### ISSUE TITLE
how to activate the beta component?

### ISSUE THREAD

**Issue by athebe** [plugwise/plugwise-beta#195]
Hi, 
i've installed through HACS the beta component. 
Updates are coming through HACS so thats ok. 

How to activate the usb stick , if i go to home assistant=> conf => integrations  i only find plugwise and not plugwise beta? 

If i select plugwise i assume i'm using the main component and not the beta one?
i'm looking for the support circle  in the energy management system.

**Comment by brefra** [comment]
@athebe you should be able to select the "Plugwise Beta" from the list. Most likely you did not restart Home Assistant after installing from HACS. This is required to have the beta version showing in the integration list.

**Comment by athebe** [comment]
have already restarted and even proxmox reboot... still not visible...

**Comment by athebe** [comment]
solved: had in custom components another dir used by plugwise and renamed it to plugwise_old. 
I deleted everything and renamed it back to plugwise, then reinstall and now it works.
