### ISSUE TITLE
Battery-values are not shown in %

### ISSUE THREAD

**Issue by bouwew** [plugwise/plugwise-beta#20]
This is what I see:
![image](https://user-images.githubusercontent.com/11290930/78452776-9629a780-768d-11ea-8a6f-52dd1f8f65a1.png)

In the data the value looks like this: `"battery": 1.0`.
It should show 100%.

**Comment by CoMPaTech** [comment]
True, we live 'm floating, so we should *100 and int them, issue should move to Plugwise-Smile

**Comment by bouwew** [comment]
Fixed by #21
