### ISSUE TITLE
[BUG] Plugwise Anna not updating state

### ISSUE THREAD

**Issue by dmotion77** [plugwise/plugwise-beta#214]
**Describe the bug**
Plugwise Anaa not updating state on home assistant interface. On stable working, in beta not. I'm using (latest) beta because I have also a P1.

**Evidence**
No errors in logs. 

![anna-heating-no-status](https://user-images.githubusercontent.com/79809499/141693315-487e8199-8010-4eb7-8b18-b2a333f442c8.png)

The state of device is always the same, heating or idle. 

Using latest stable HA on intel Nuc.

**Comment by bouwew** [comment]
No bug, "Inactief" means that there is no week-schedule active and "Thuis" is showing the selected preset.
The heating-state is not shown on the HA Climate card.

If you want to show the heating state, use the Simple Thermostat Card: https://github.com/nervetattoo/simple-thermostat

**Comment by bouwew** [comment]
Closed, not a bug.
