### ISSUE TITLE
[BUG] Plugwise Anna climate entity indicating wrong status; idle while connected Elga heatpump is heating

### ISSUE THREAD

**Issue by bouwew** [plugwise/plugwise-beta#215]
**Describe the bug**
For some time I have noticed that the climate.anna entity in HA dashboard is indicating the incorrect status; after some time in 'heating' status the integration show status 'idle' while the physical thermostat as well as the Plugwise Home app is indicating that the connected heatpump (Techneco Elga) is still heating. Auxiliary Modulation Level is > 0 and thus representing status of heatpump correct.

Copy of https://github.com/home-assistant/core/issues/59711

**Comment by bouwew** [comment]
@huub66

Your reported issue should be fixed in the backend plugwise library v0.15.2
Will soon to be integrated in plugwise-beta v0.19.5-alpha4, later today/tonight.
Enable "Show Beta" in HACS to see alpha/beta releases.

Please test this version when it's available and let us know your results.

P.S.: do you also happen to use the cooling function of the Elga?

**Comment by huub66** [comment]
Clear, will do.

Yes I do use cooling, that seems to work and indicate status properly (as far as I can recall)

**Comment by bouwew** [comment]
Ok that's good to know. Regarding the cooling function, on second thought, I guess you can't really help us out. The function we still want to implement is specific for an Adam, we will need to find a user that has an Adam connected to an Elga.

Yes, the cooling state should be shown properly.
The heating-state was not properly shown due to Plugwise not being fully consistent in their software.
Up to now we have been using one specific parameter in `http://<smile-ip-adress>/core/appliances` as the indicator for heating. This is the correct parameter to use, we think, for the traditional gas-fired heating systems.
But it looks that Plugwise is using a different parameter in the case of the Elga / a heatpump. 
So we'll adapt :)

**Comment by huub66** [comment]
Downloaded and tested; issue is resolved. Thanks!

**Comment by bouwew** [comment]
Thanks! Glad to read that it's resolved. Be so kind to close the issue in the HA Core github.

Now, if you don't mind me asking, how do you switch from heating to cooling in your system? Is that done automatically? Or manually? Can you tell me more about this?

**Comment by bouwew** [comment]
@huub66 In de Plugwise data zie ik een parameter `cooling_activation_outdoor_temperature`, dit is denk ik een automatische omschakeling? Klopt dat?

**Comment by huub66** [comment]
> @huub66 In de Plugwise data zie ik een parameter `cooling_activation_outdoor_temperature`, dit is denk ik een automatische omschakeling? Klopt dat?

Ja klopt, er kan een max en min buiten temp worden ingesteld in de plugwise app waarbij wordt ingesteld waarboven koeling wordt in- of uitgeschakeld

**Comment by bouwew** [comment]
Kunt je een plaatje van die instellingen posten?
En kun je evt nagaan wat de namen van die instellingen zijn in /core/appliances?

**Comment by bouwew** [comment]
@huub66 Wat is het doel van de min buiten temp? Dat snap ik niet helemaal?
Max buiten temp snap ik, dan schakel je om naar koelen.
Of is het zo wanneer je onder de min buiten temp komt dat het systeem dan weer overschakelt naar verwarmen?
Wat zijn bij jouw de ingestelde waarden van de beide temperaturen?

**Comment by huub66** [comment]
Inderdaad. Bij mij gaat de warmtepomp automatisch in koelmodus bij een buitentemp van 25 graden C en weer uitgeschakeld bij een buitentemp van 13 graden C. Dit is vrij instelbaar. 
Daarnaast zijn 'uitschakelvoorwaarden' instelbaar; warmtepomp gaat uit onder een buitentemp van -8 graden C en CV ketel blijft uit bij een buitentemp > dan 20 graden C.

**Comment by bouwew** [comment]
Bedankt! De situatie wordt me langzaam steeds duidelijker.
Maar, ik snap de 13 graden grens niet helemaal. Of misschien toch wel... dit kan ook de temperatuur 's nachts zijn. Dat is een stukje hysterese, je wilt voorkomen dat het systeem elke dag gaat schakelen tussen koelen en verwarmen denk ik.

Hmm, dat compliceert de situatie toch wel een beetje denk ik. Jammer dat er in de Plugwise data niet een variabele zit die aangeeft welke mode (koelen/verwarmen) actief is. We zullen die zelf moeten inbouwen.

Ik kom er nu wel uit denk ik, bedankt voor de info!

**Comment by bouwew** [comment]
@huub66 Zou ik jouw hulp nog eens mogen inroepen?

Ik zou graag de xml-data van jouw Anna willen inzien om uit te vinden hoe ik bij een verbonden warmtepomp kan detecteren of er een koelfunctie aanwezig is. Ik heb dit nu eindelijk duidelijk hoe ik dat bij een Adam kan detecteren, via een andere bezitter van een Adam + Elga Ace. Maar het is me nog steeds niet duidelijk hoe ik dat bij de Anna kan herkennen.

Zou je de xml-data van jouw Anna willen capturen? Zie hier https://github.com/plugwise/python-plugwise/tree/main/userdata voor info, even doorscrollen naar het kopje "Sharing". 
Ik hoef de data van /core/direct_objects niet, de rest wel.

**Comment by huub66** [comment]
excuus deze is blijven liggen en door vakantie niet meer gezien
is het nog nodig? zo ja, zal ik dat vandaag of morgen even doen

> @huub66 Zou ik jouw hulp nog eens mogen inroepen?
> 
> Ik zou graag de xml-data van jouw Anna willen inzien om uit te vinden hoe ik bij een verbonden warmtepomp kan detecteren of er een koelfunctie aanwezig is. Ik heb dit nu eindelijk duidelijk hoe ik dat bij een Adam kan detecteren, via een andere bezitter van een Adam + Elga Ace. Maar het is me nog steeds niet duidelijk hoe ik dat bij de Anna kan herkennen.
> 
> Zou je de xml-data van jouw Anna willen capturen? Zie hier https://github.com/plugwise/python-plugwise/tree/main/userdata voor info, even doorscrollen naar het kopje "Sharing". Ik hoef de data van /core/direct_objects niet, de rest wel.

**Comment by bouwew** [comment]
Nee, volgens mij niet meer nodig, ik heb op dit moment voldoende in beeld hoe dit zou moeten werken.
Dit is allemaal geimplementeerd in plugwise-beta v0.19.8
Hoe werkt deze versie bij jouw? Zou jij eens goed naar de werking/details in jouw systeem willen kijken?

**Comment by bouwew** [comment]
@huub66 Never mind, het werkt niet. Gisteren kwam ik erachter dat ik een fout heb gemaakt waardoor het detecteren van het inschakelen van de koelfunctie niet zal werken.
Ik laat binnenkort wel even weten wanneer er een versie beschikbaar is die wel zou moeten werken :)
