### ISSUE TITLE
 My Circle devices are not available [BUG]

### ISSUE THREAD

**Issue by willsmarthome** [plugwise/plugwise-beta#221]
Hello,

When I install plugwise-beta version 0.19.7 my circle devices are not available.
The same problem when I install the beta releases 1 - 4.
With version 0.19.6 the circle devices are working perfect.

Is this a known problem?

**Comment by bouwew** [comment]
@willsmarthome Is there any information in the LOGBOEK that can help to pinpoint the problem?
And, you are using a Stretch, not a Stick, correct?

**Comment by willsmarthome** [comment]
Yes, I'am using a Stretch.
HA is running on core-2021.12.2.

There is no additional informatie in the logging.
I can turn on the debug logging and install version 0.19.7.

**Comment by bouwew** [comment]
That is strange! Did maybe the sensor_names change to sensor_name_2 versions?

**Comment by willsmarthome** [comment]
> That is strange! Did maybe the sensor_names change to sensor_name_2 versions?

No time now, busy with work. 
Tomorrow morning I'll do the upgrade again and see what happens.

**Comment by willsmarthome** [comment]
Just installed core-2021.12.3. after reboot installed plugwise-beta version 0.19.7.
Devices are available and nog error messagess in the logging.
Strange!?!?

**Comment by bouwew** [comment]
Strange, yes and no: v0.19.6 is meant for 2021.11 and older, it should work with 2021.12 despite the error I think.
And v0.19.7 and up are meant for 2021.12 and up. Glad to see that it's working again :)

Devices not available can mean that the connection between the Stretch and HA Core has been lost or that the data is not yet available. That leads to the `unavailable` for the states. Did you see this directly after a reboot of HA Core?

**Comment by willsmarthome** [comment]
Now the devices are immediately available. 
In the previous situation, the devices remained unavailable, even after a long time and restarting the integration and the HAS.
