### ISSUE TITLE
[BUG]: `opentherm_heating` incorrectly enabled when using only hot tap water with Plugwise Anna thermostat

### ISSUE THREAD

**Issue by Meessen1** [plugwise/plugwise-beta#250]
### Describe the bug.

The `opentherm_heating` state should only be enabled when heating (Anna radiator icon), but it also enabled when using just hot tap water (Anna tap icon). This might be a problem specific to Anna as in [this discussion](https://community.home-assistant.io/t/plugwise-anna-heating-state-incorrect-after-core-update-2022-3/402064/5) it is indicated that it works correctly for Adam.

When just tapping hot water `opentherm_heating` `opentherm_flame_state` `opentherm_dhw_state` are enabled.
When just heating `opentherm_heating` `opentherm_flame_state` are enabled.

Because of this I cannot create a reliable automation for enabling the floor heating pump when the thermostat is heating.
Additionally the HA Anna UI card shows that the system is heating when using hot tap water.

Attached:
- Two screenshots of the state changes in HA logs, one for hot tap water and one for heating. 
- Plugwise diagnostic data logs for 3 situations; when using just hot tap water, when just heating and when doing neither.

### What version of Home Assistant Core has the issue?

core-2022.3.4

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

Home Assistant Core

### What kind of Plugwise device is having issues?

Smile: Anna

### What firmware version is your Plugwise product at?

4.0.27

### Diagnostics information

[AnnaLogs.zip](https://github.com/plugwise/plugwise-beta/files/8255102/AnnaLogs.zip)

**Comment by bouwew** [comment]
Thanks for providing the data, I'll take a look at it now.

**Comment by bouwew** [comment]
Ok, I've looked at the data. And I indeed found a bug in the plugwise-backend library.

I will fix this bug in the backend. But it will take some time before this ends up in HA Core. I would assume the fix will be in Core release 2022.4.

If you want to test this earlier, you can test it by installing Plugwise-beta.
If you want to do that, let me know and I'll inform you about which pw-beta version to test.

**Comment by bouwew** [comment]
Please test plugwise-beta v0.21.5a1

Instructions are here: https://github.com/plugwise/plugwise-beta/blob/main/README.md
Scroll down to `How to Install`.

**Comment by bouwew** [comment]
Thanks for testing! And nice to hear that it's working :)

**Comment by bouwew** [comment]
Closing this issue as the solution is available in both Plugwise-beta and in Core Plugwise of HA Core 2022.4.0b0.
