### ISSUE TITLE
[FEATURE]: Adam more controls/status

### ISSUE THREAD

**Issue by malosaa** [plugwise/plugwise-beta#254]
### Describe the solution you are looking for

For example, on the homeseer plugin i can use the regulation state of the adam.
like: Bleeding hot, Bleeding cold, Off and heating.

If i click the Bleeding hot button, my adam goes to power heat my Nefit NXT so it heats quicker in my home.

In /core/appliances when i select bleeding hot in homeseer it shows up in adam core/appliances

```
<type>regulation_mode</type>
<unit/>
<updated_date>2022-03-17T10:29:22.828+01:00</updated_date>
<last_consecutive_log_date>2021-12-05T20:46:34.641+01:00</last_consecutive_log_date>
<interval/>
<regulation_mode_control id="57451d0a44da47e7a3d00c760dae7649"/>
<period start_date="2022-03-17T10:29:22.828+01:00" end_date="2022-03-17T10:29:22.828+01:00">
<measurement log_date="2022-03-17T10:29:22.828+01:00">bleeding_hot</measurement>
</period>
```

And this is what u need to add, its in the core/appliances 

```

<actuator_functionalities>
<regulation_mode_control_functionality id="7dd2c3b964c049e7923cfdae2ccc6908">
<regulation_mode_control id="57451d0a44da47e7a3d00c760dae7649"/>
<updated_date>2022-03-17T10:29:22.828+01:00</updated_date>
<type>regulation_mode</type>
<mode valid_until="2022-03-17T10:34:22.831+01:00">bleeding_hot</mode>
<allowed_modes>
<mode>heating</mode>
<mode>off</mode>
<mode>bleeding_cold</mode>
<mode>bleeding_hot</mode>
</allowed_modes>
</regulation_mode_control_functionality>
```

Most of them are in core/appliances

There are more functionality's what can be added, just look up this:
`thermostat_functionality id=`

Here are the 4 things i love to see added to the adam:

- Domestic hot water setpoint
- Maximum boiler temperature set
- Regulation mode on/off (to control the regulation)
- Regulation mode (Bleeding hot, bleeding cold, heating, off)

I did send the full output on your email

regards and no hurry take your time.

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor)

### What firmware version is your Plugwise product at?

2022-03-05

### Your setup

Adam only with Anna, but anna disabled in HASS

**Comment by bouwew** [comment]
@malosaa I know roughly how the communication works :)

I tried to make it work for max boiler temperature and dhw setpoint. I could change one but I could not change the other.
I did capture the http-data that the Adam-website sent when I would change the setpoints. My code did sent exactly the same but one setpoint did not change. I'll try again soon, maybe it was a bug in de Adam software.

Another problem is how to do this in HA. Could be via service but I would prefer to do it via something on the frontend.

More later...

**Comment by malosaa** [comment]
> Would the present homeseer plugwise developer be willing to share parts of his code?
> 
> I've asked Rien du Prie who claimed that he had written the homeseer plugwise code, but he stopped responding to my questions.

Rien did quit a long while ago,
As stefan did renew the code for homeseer.
https://shop.homeseer.com/products/stefxx-plugwise-pro-software-plugin-for-hs4
But its a payed plugin.

Homeseer mainly runs on vb all plugins aswell.
I can see and look if i have my old vb script i used before how i handle the devices, i had it before for the p1 and adam, i did make a lot of addons on homeseer on domoticaforum.

But yeah try to contact stefxx he is now the code owner, and he is dutch 2.

**Comment by malosaa** [comment]
well i did run it in debug mode and i selected the bleeding hot mode,
this shows up, dunno if its usefull for you

```
3-17-2022 17:22:09
Plugwise Pro
Info
Plugwise Adam (1): Send: http://192.168.1.20/core/appliances
3-17-2022 17:22:09
Plugwise Pro
Info
Plugwise Adam (1): Send: http://192.168.1.20/core/modules
3-17-2022 17:22:09
Plugwise Pro
Info
Plugwise Adam (1): Send: http://192.168.1.20/core/rules
3-17-2022 17:22:09
Plugwise Pro
Info
Plugwise Adam (1): Send: http://192.168.1.20/core/locations
3-17-2022 17:22:09
Plugwise Pro
Info
Plugwise Adam (1): Send: http://192.168.1.20/core/appliances;type=gateway/regulation_mode_control: "300bleeding_hot"
3-17-2022 17:22:09
```

**Comment by bouwew** [comment]
Setting the regulation mode is working in the backend. Not yet working in pw-beta.

Your debug info is not really helpful because the information you provide does not provide enough details.
Although it might point me to a solution for the not-working setpoint :)

Do you have the possibility to install Wireshark?

**Comment by bouwew** [comment]
A Domestic Hot Water Comfort mode switch does already exist: see the DHW Comfort mode switch under the OpenTherm device.

**Comment by malosaa** [comment]
> Setting the regulation mode is working in the backend. Not yet working in pw-beta.
> 
> Your debug info is not really helpful because the information you provide does not provide enough details. Although it might point me to a solution for the not-working setpoint :)
> 
> Do you have the possibility to install Wireshark?

Yeah i can install wireshark, let me know what i need to do so i can help you.
Yeah i ment not the Hot Water COmfort mode switch, i ment an other switch to select eco mode, i did mistake on that one.

regards

**Comment by bouwew** [comment]
I'm just curious, how often do you change settings in your system? And with what purpose?
I normally never change anything. The DHW Comfort switch is always off, the system is always in Eco mode.
Maybe once every 5 years I change the max boiler temperature setpoint. Only when the winter is very cold.

**Comment by malosaa** [comment]
> I'm just curious, how often do you change settings in your system? And with what purpose? I normally never change anything. The DHW Comfort switch is always off, the system is always in Eco mode. Maybe once every 5 years I change the max boiler temperature setpoint. Only when the winter is very cold.

Well i did change it alot when i was on homeseer, as i had to find the perfect settings.
Right now everything is setup right for the past 2 year, and got a lot of money back last 2 years.

Because there was no option to use bleeding hot mode, i buyed 2 electrical heaters for my house, as i have a lot of solar panels and my Power/gas provider  pays me the full kwh back that i used.
So i slowly move to electrical instead of using gas, as the price is above 2euro now a m3.

but for now its gonna be warmer so no heater needed anymore :)

**Comment by bouwew** [comment]
Ok, you can try pw-beta v0.22.0a1, it contains a selector for the heating mode.
And please note, the bleeding-options are only active for a certain time: 300 seconds or minutes? I'm not sure.

**Comment by malosaa** [comment]
> Ok, you can try pw-beta v0.22.0a1, it contains a selector for the heating mode. And please note, the bleeding-options are only active for a certain time: 300 seconds or minutes? I'm not sure.

ok ill test, yes its 300 seconds

**Comment by malosaa** [comment]
> Ok, you can try pw-beta v0.22.0a1, it contains a selector for the heating mode. And please note, the bleeding-options are only active for a certain time: 300 seconds or minutes? I'm not sure.

i think it works, as the intended boiler temp goes quickly up when used bleeding_hot

i did notice a thing, this sensor sensor.auxiliary_device_state for me is unavailable,  i did not see this before 
its on the same page where dhw-comfort  switch is

**Comment by bouwew** [comment]
Yes, that one has been removed, it's replaced by a binary_sensors for heating.

**Comment by bouwew** [comment]
The possibility to set the max boiler temperature was added in v0.22.0a6.

**Comment by malosaa** [comment]
> The possibility to set the max boiler temperature was added in v0.22.0a6.

Thanks, i will check it out once i'm home

regards

**Comment by malosaa** [comment]
Sorry for the very late reply, due the busy schedule i have.


I did see an update in HACS, i wait till its beta.

Regards

**Comment by malosaa** [comment]
yes its good, we can close this one :) thanks you guys
