### ISSUE TITLE
Probably a bug.

### ISSUE THREAD

**Issue by malosaa** [plugwise/plugwise-beta#273]
### Describe the bug.

Hi bouwe, 

I noticed the Peak does not update, only offpeak now.. don't know why, looks like Peak and Offpeak are mixed, or i'm not looking right.

this is at 10:40 AM eu time

![image](https://user-images.githubusercontent.com/13116501/163668457-a23065b3-fd51-4d93-9355-e645324e633a.png)

### What version of Home Assistant Core has the issue?

2022.4.4

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: P1

### What firmware version is your Plugwise product at?

Firmware: 2.1.20

**Comment by bouwew** [comment]
The weekend is off-peak tariff.

**Comment by malosaa** [comment]
OMG u right, damn what an embarrassment.

I probably need to sleep again hahaha
I quick close this issue lol

thanks for the reply tho.

**Comment by bouwew** [comment]
No problem :)
