### ISSUE TITLE
[BUG]: Stretch: Circle+ is missing

### ISSUE THREAD

**Issue by bouwew** [plugwise/plugwise-beta#277]
### Describe the bug.

As reported by user Ollem, the Circle+ is not shown in HA.

### What version of Home Assistant Core has the issue?

2022.4

### What was the last working version of Home Assistant Core?

Unknown

### What type of installation are you running?

Home Assistant Core

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Stretch

### What firmware version is your Plugwise product at?

3.1.11

**Comment by bouwew** [comment]
Fixed via https://github.com/plugwise/python-plugwise/pull/184

**Comment by willsmarthome** [comment]
Same problem here.
I have installed 0.22.3 and still the Cirlce+ is missing.
The Circle+ is visible in Stretch available.

**Comment by bouwew** [comment]
@willsmarthome Please test plugwise-beta v0.22.4b0, that version should  work.

**Comment by willsmarthome** [comment]
@bouwew, after installing:  plugwise-beta v0.22.4b0 problem solved.

**Comment by bouwew** [comment]
Thanks for confirming that the fix is working :)
I will release v0.22.4
