### ISSUE TITLE
water_pressure is not measured in bar

### ISSUE THREAD

**Issue by wburgers** [plugwise/plugwise-beta#28]
The water pressure is reported as mbar, which is not the correct unit.
It should be bar.
![image](https://user-images.githubusercontent.com/2129305/78883815-49ade580-7a5a-11ea-89d0-e084d81eaf6c.png)

Or the value should be x1000, that is also fine of course 😛

**Comment by wburgers** [comment]
Fixed in #30 
Damn you guys work fast!

**Comment by CoMPaTech** [comment]
Tnx for the compliments @wburgers - we've started our upstream PR as well so it might be busy next two weeks until HA 0.109 :)
