### ISSUE TITLE
[BUG]: Heating-state is not correct for Elga

### ISSUE THREAD

**Issue by bouwew** [plugwise/plugwise-beta#320]
### Describe the bug.

As reported bij @huub66, the heating_state binary_sensor (based on the `intended_central_heating_state` key) is not correctly displaying the heating_state:
https://community-assets.home-assistant.io/original/4X/8/b/c/8bc2776df866d2f77fa9adf5ec6878239712cca1.png

I appear that the `central_heating_state` key represents the heating_state better:
https://community-assets.home-assistant.io/original/4X/f/c/4/fc4b947022942c850baf4e63a443ffd3853c1f05.png

### What version of Home Assistant Core has the issue?

2022.11.4

### What was the last working version of Home Assistant Core?

Unknown

### What type of installation are you running?

Home Assistant Supervised

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Anna

### What firmware version is your Plugwise product at?

4.3.7

**Comment by bouwew** [comment]
I will recheck the status from @huub66.

**Comment by bouwew** [comment]
Update: still not OK. I've released v0.34.99a0 for further testing.
This release adds:
An extra sensor: Elga status code
Two extra binary_sensors: Central heating and Intended central heating

With these extra's I hope to get a better idea on how to show the various states correctly.

**Comment by huub66** [comment]
Have tested with v0.34.99a0. The "heating_state binary_sensor" is not displaying correct stil. When DHW sensor is on, heating_state_binary_sensor is set to off, even though heatpump is running at that time (DHW is supplied by a connected parallel conventional gas boiler with Techneco Elga heatpump). 

See below graph for indication of behavior; at approx 20h DHW is set to on while heatpump is running but at the same time heating state binary sensor is set to off.

![image](https://user-images.githubusercontent.com/68535665/228318335-e92a108a-8432-46cb-bd27-4ffc9393cb5e.png)

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/68535665/228318772-30dcc60a-db1e-4db0-9582-58a497cee42d.png">

**Comment by bouwew** [comment]
More data provided by @huub66:
![image](https://user-images.githubusercontent.com/11290930/230784487-24cfdd9d-7905-47d5-b8a9-0ff01224bcf7.png)

**Comment by bouwew** [comment]
Fixed via #376
