### ISSUE TITLE
[BUG]: Probably the cost device has an issue

### ISSUE THREAD

**Issue by malosaa** [plugwise/plugwise-beta#321]
### Describe the bug.

Hi guys,

I have an weird issue during a migration to MARIADB
i'm not sure but i need to ask this question as this issue can't be resolved, and i'm out of options.
i did fully check the database, but after looking at the data itself its messed up.

My energy dashboard does report wrong energy costs, when inspecting i did see that the plugwise add-on provide cost entities and my home assistant is using them.

Where does it get it's data from ? 

### What version of Home Assistant Core has the issue?

2022.11.2

### What was the last working version of Home Assistant Core?

2022.11.2

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: P1

### What firmware version is your Plugwise product at?

last

### Logging

no

### Diagnostics information

no

### Additional information

no

**Comment by bouwew** [comment]
The DSMR provides the type of tariff that is active: peak or off-peak.
Does that answer your question?

**Comment by malosaa** [comment]
Many thanks for your reply, so i close this issue it's probably a homeassistant bug then. 
regards and thanks for the reply
