### ISSUE TITLE
[BUG]: Issue with gas last 4 days

### ISSUE THREAD

**Issue by malosaa** [plugwise/plugwise-beta#368]
### Todo

I did notice just now that since 4 days it does not update the gas.
I did not update the beta at all, it just stopped.

I did check this issue on all 3 systems and all 3 not updating.

I'm using the smile v2 for ages never had problems.
so here is the screenshot of my smile gas 
![image](https://user-images.githubusercontent.com/13116501/227719868-8197473d-e7fa-4f9d-9151-a28b1d562b3d.png)

and in home assistant the value is 
![image](https://user-images.githubusercontent.com/13116501/227719889-a25172a6-2bd3-43b1-8d2f-d348d0b606b1.png)

I'm was on v0.32.0 plugwise beta and now I updated the beta to your last stable version and still an issue.
The only thing i did 4 days ago was update home assistant.

![image](https://user-images.githubusercontent.com/13116501/227720394-e3f9e023-e5b6-4c30-af8f-4a77b8f964d8.png)

 **smileIP/core/modules** **_(here is the correct data)_**
![image](https://user-images.githubusercontent.com/13116501/227720618-cfca9906-6531-4267-a359-cc4d4edbdab5.png)

**_core/direct_objects_**  **bad data**
If i look at it now in that page the value is in there and wrong.

![image](https://user-images.githubusercontent.com/13116501/227721018-c0bee4eb-e0c8-41e2-a6c6-3ed917629523.png)
In 2021 we had the same issue because you did use the data from here 
 thats not good if u use the smile v2.

**Comment by bouwew** [comment]
Yes, I have this too now and then. Not very often, maybe once a year?

The only thing that I found that helps is to power off the Smile P1, wait 10 seconds, then power the Smile P1 back on.

Also, the data is taken from /core/locations, not from /core/domain_objects.

**Comment by malosaa** [comment]
Ok lets try it out, i report back :)

**Comment by malosaa** [comment]
Sadly i did just reconnect it, still old value.
Even when putting hot water on it doesn't change at all.
Really weird

**Comment by bouwew** [comment]
Ok, I don't remember well, try pulling out the P1-cable from the smart meter for a few minutes.

**Comment by bouwew** [comment]
I'll see if I can find some time to take the data from /core/modules...

**Comment by malosaa** [comment]
I did try for 5 minutes, sadly still no update..
Weird the last time i had this issue was almost 2 years ago.. 

Just take your time and check it out when u have time, no rush.

**Comment by bouwew** [comment]
Please test v0.34.8b1.
This new version collects the P1-data from /core/modules.
Looks like it's working normally on my P1 with firmware v2.1.20

**Comment by malosaa** [comment]
> v0.34.8b1, or b2.

Yes b1 works  thanks, did you change something else on b2 ?

**Comment by bouwew** [comment]
Nice, thanks for letting me know :)

b2 has a Stick-related update, no impact on the P1.

**Comment by malosaa** [comment]
Man thanks for your great service and time :) 
Really appreciatie it !

Have a nice wonderful day :)

**Comment by bouwew** [comment]
Fixed in v0.34.8

**Comment by malosaa** [comment]
@bouwew 

Sorry to ask you again, just want to give you a heads up that if i update past 0.34.8 the gas will again not be detected.
regards

**Comment by bouwew** [comment]
Ok, strange, I will have a look.

**Comment by malosaa** [comment]
no worries, i reverted back to the last version. 
take your time its not a big issue :)

**Comment by bouwew** [comment]
@malosaa To be honest, I have no idea what could be wrong.

Can you please send me the diagnostics-outputs for both versions v0.34.8 and v0.40.3?
Maybe I can spot a difference in the two files that leads me to the root-cause of the problem that you are seeing.

**Comment by bouwew** [comment]
@malosaa I've been looking at code-changes that might cause the new issue.
Looking at these code-changes, does v0.34.9 already show the new issue?

**Comment by malosaa** [comment]
@bouwew 

I was a bit out of time,
I will check tomorrow morning, i let you know asap.
Thanks for the message.

**Comment by malosaa** [comment]
Sorry for the late reply, i was really busy.. sorry.

This is weird, i updated the one on my test server 0.40.4 and it works again 👍 
really don't know why that specific other version did not work.

if i see an issue, i report on here, but i think its ok now.

Regards

**Comment by bouwew** [comment]
That's good to read! Thanks for letting me know :+1:
