### ISSUE TITLE
[TODO]: `max_dhw_temperature` in upcoming Core PR

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/plugwise-beta#400]
Note on 518c54c still needs `max_dhw_temperature` change in https://github.com/plugwise/python-plugwise/pull/309/files to be applied (i.e. python-plugwise generates this fixture but test in number-domain fails). `prettier` should now no longer tinker with the generated fixtures from https://github.com/plugwise/python-plugwise/pull/311

_Originally posted by @CoMPaTech in https://github.com/plugwise/plugwise-beta/issues/397#issuecomment-1535481625_

**Comment by bouwew** [comment]
Added to Core via https://github.com/home-assistant/core/pull/98092
