### ISSUE TITLE
Some entities are missing 

### ISSUE THREAD

**Issue by Wishdoc** [plugwise/plugwise-beta#417]
### Describe the bug.

Following on issue #301 the following entities are not available anymore.  (this also happend in 

Anna - cooling setpoint
Anna - heating setpoint
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/eba8696b-4285-4e83-8b06-b92556735b2e)

Opentherm - Cooling switch
Opentherm - Domestic Hot Water is availeble in Dutch, so this is not actually missing. 
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/4b7f22e1-f81d-4a83-83b7-846674032739)

The only issue's in logfile are related to automations and some user issue's. So i activated debugging and add the logfile

 
[home-assistant_2023-06-21T18-57-57.781Z.log](https://github.com/plugwise/plugwise-beta/files/11823870/home-assistant_2023-06-21T18-57-57.781Z.log)
[home-assistant_plugwise_2023-06-21T19-01-33.985Z.log](https://github.com/plugwise/plugwise-beta/files/11823896/home-assistant_plugwise_2023-06-21T19-01-33.985Z.log)

### What version of Plugwise Beta are you using?

V0.40.3

### What was the last working version of Plugwise Beta (or Core if not using beta before)?

v0.34.11a4

### What version of Home Assistant Core are you using?

2023.6.2

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Anna

### What firmware version is your Plugwise product at?

4.3.13

**Comment by bouwew** [comment]
@Wishdoc Thanks, I'll have a look.

**Comment by bouwew** [comment]
@Wishdoc please try plugwise-beta v0.40.4a0.

Please remove the domestic_hot_water_setpoint sensor, this one is no longer provided when there exists a max_dhw_temperature number.

**Comment by Wishdoc** [comment]
@bouwew , installed this version and the problems are solved. All entities are available and work fine. 

Thanks
