### ISSUE TITLE
[BUG]: Heating and cooling mode switched with Plugwise Anna icw Elga Heatpump

### ISSUE THREAD

**Issue by huub66** [plugwise/plugwise-beta#512]
### Describe the bug.

The plugwise climate entitiy remains in cooling mode while Pluwise Anna and connected heatpump are in heating mode.
![Screen Shot 2023-10-25 at 13 18 08 PM](https://github.com/plugwise/plugwise-beta/assets/68535665/ccb792bd-be41-43f0-a88c-9ea6ce1cfbeb)

### What version of Plugwise Beta are you using?

0.43.0

### What was the last working version of Plugwise Beta (or Core if not using beta before)?

unknown

### What version of Home Assistant Core are you using?

core-2023.10.5

### What type of installation are you running?

Home Assistant Core

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Anna

### What firmware version is your Plugwise product at?

2018-02-08T11:15:53+01:00

### Logging

[custom_components.plugwise] Smile Anna data: PlugwiseData(gateway={'gateway_id': 'ba0bfc315727476285ce6d85fde5d37d', 'item_count': 66, 'notifications': {}, 'smile_name': 'Smile Anna', 'heater_id': '993109372f6e49299c7a90bc12bf977b', 'cooling_present': True}, devices={'ba0bfc315727476285ce6d85fde5d37d': {'dev_class': 'gateway', 'firmware': '4.4.1', 'hardware': 'AME Smile 2.0 board', 'location': '91bec21b69214398a90c5fc4ad09dd2e', 'mac_address': 'D40FB201313A', 'model': 'Gateway', 'name': 'Smile Anna', 'vendor': 'Plugwise', 'binary_sensors': {'plugwise_notification': False}, 'sensors': {'outdoor_temperature': 10.1}}, '993109372f6e49299c7a90bc12bf977b': {'dev_class': 'heater_central', 'location': '91bec21b69214398a90c5fc4ad09dd2e', 'model': 'Generic heater/cooler', 'name': 'OpenTherm', 'vendor': 'Techneco', 'binary_sensors': {'dhw_state': False, 'heating_state': True, 'compressor_state': True, 'cooling_state': False, 'cooling_enabled': True, 'slave_boiler_state': False, 'flame_state': True}, 'sensors': {'water_temperature': 24.5, 'dhw_temperature': 57.7, 'intended_boiler_temperature': 0.0, 'modulation_level': 35, 'return_temperature': 23.3, 'water_pressure': 1.1, 'outdoor_air_temperature': 10.9}, 'switches': {'dhw_cm_switch': False}, 'max_dhw_temperature': {'setpoint': 50.0, 'resolution': 0.01, 'lower_bound': 50.0, 'upper_bound': 60.0}, 'maximum_boiler_temperature': {'setpoint': 50.0, 'resolution': 0.01, 'lower_bound': 50.0, 'upper_bound': 80.0}, 'available': True}, 'dd9975713bf3499b9d7e68299c2526d7': {'dev_class': 'thermostat', 'firmware': '2018-02-08T11:15:53+01:00', 'hardware': '6539-1301-5002', 'location': '7f24f49cdea846f79f9bc03a8425152c', 'model': 'ThermoTouch', 'name': 'Anna', 'vendor': 'Plugwise', 'sensors': {'temperature': 19.9, 'illuminance': 2.75, 'cooling_activation_outdoor_temperature': 24.0, 'cooling_deactivation_threshold': 12.0, 'setpoint_low': 4.0, 'setpoint_high': 19.5}, 'temperature_offset': {'lower_bound': -2.0, 'resolution': 0.1, 'upper_bound': 2.0, 'setpoint': -0.5}, 'thermostat': {'setpoint_low': 4.0, 'setpoint_high': 19.5, 'resolution': 0.1, 'lower_bound': 4.0, 'upper_bound': 30.0}, 'preset_modes': ['no_frost', 'vacation', 'asleep', 'home', 'away'], 'active_preset': 'home', 'available_schedules': ['None'], 'select_schedule': 'None', 'mode': 'heat_cool'}})

**Comment by bouwew** [comment]
@huub66 Can you please look in `http://<smile_ip>/core/appliances` and find the xml_key `cooking_enabled`.
What is the `measurement`-value for this key? On or off?

**Comment by bouwew** [comment]
Hmm, I have this key in my system as well. While I have no cooling-capability. Confusing...

**Comment by bouwew** [comment]
@huub66 Please test pw-beta v0.43.1a0. Does this update correct the reported issue?

**Comment by huub66** [comment]
> @huub66 Please test pw-beta v0.43.1a0. Does this update correct the reported issue?

Yup, solved. Thanks!
Cooling setpoint is not synchronized during heating mode though, is this expected behavior?

**Comment by bouwew** [comment]
Yes, that is already the default behavior for some months. This is because Plugwise does not support changing the cooling-setpoint in heating-mode and also the other way around. 
If it is synchronized, users will try to change it and then an error pops up, which was meant to "teach" the user that changing the non-active setpoint is not possible, but that did not work out well :)
So that's why I fixed the non-active setpoints to 30 and 4 degrees.

**Comment by bouwew** [comment]
Fixed in pw-beta v0.43.1
