### ISSUE TITLE
[FEATURE]: Evaluate new 'add pause' functionionality

### ISSUE THREAD

**Issue by Torch1969** [plugwise/plugwise-beta#523]
### Describe the solution you are looking for

Since beginning of 2023, the Plugwise app and html interface feature a pause function to pause the current schema as described here:
[https://community.homey.a...he-designated-scene/62615](https://community.homey.app/t/plugwise-pause-button-later-pickup-the-designated-scene/62615)
And here:
[markkkooo in "Plugwise schema oppakken bij thuiskomst"](https://gathering.tweakers.net/forum/list_message/74155404#74155404)

Please add this function to HA integration of Plugwise

### What type of installation are you running?

Home Assistant Container

### How did you install plugwise-beta?

Home Assistant Core

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor)

### What firmware version is your Plugwise product at?

None yet

### Your setup

No HA setup yet.

**Comment by CoMPaTech** [comment]
Hi @Torch1969 and thanks for the suggestion. @bouwew spotted the indications for this as well and we briefly discussed it earlier today.

From the looks of it this is something we could build but can be comprised in a simple automation as well. Basically Plugwise put a wrapper on two existing functions. Disabling the schedule and setting to away. Which is something that can be comprised easily with an automation.

For the integration I would suggest we run this through Core to ensure upstream viability - which makes a more conscious decision for adding functionality to the `beta` stack that will not be eligible for Core.

**Comment by basvdl** [comment]
I used to put it to Heat and Away to pause the scheduling. With the latest beta version this does not work anymore for me.

If I select Off in HA for one of the Tom thermostats, it will turn off the whole heating:

<img width="235" alt="image" src="https://github.com/plugwise/plugwise-beta/assets/123811/49bdca4e-c87f-4731-a251-25a4ae5ec40d">

If I set it to Heat in HA, it will not disable the schedule and after the next refresh of Plugwise, it will show Auto again.

Also the schedule drop down does not allow you to disable the schedule:

<img width="348" alt="image" src="https://github.com/plugwise/plugwise-beta/assets/123811/55a09b39-2696-4dfa-ba21-c10787b4f38f">

manifest.json:
```
  "requirements": ["plugwise==0.34.5"],
  "version": "0.44.2"
```

**Comment by bouwew** [comment]
@basvdl Plugwise does not provide an "Off" function per thermostat. The only real "Off" function they provide is on the heating(/cooling) system ( = CV ketel of warmtepomp). Heating regulation = off means just that, the heating-system has turned the (room)heating off, for all the zones that system provides heating for.

I do realize that I have been mixing thermostat and heating-system functions. This made the most sense to me.
But I'm now also thinking about how to provide an "Off" function for one thermostat. The only option for this is using a Preset I think. We could maybe use the Preset "No-Frost" for this?

Also, if you want to turn a schedule off for one thermostat, at the moment that's only possible by clicking on the flame-icon in the climate-card or by sending a `climate.set_hvac_mode` service-command as I wrote in the Tweakers-forum.
I will investigate if it is possible to include an Off-option in the schedule-names list.

**Comment by basvdl** [comment]
Hi @bouwew ,

Clicking the flame icon on the climate card does not disable the schedule for me (anymore).

I used it in the past to temporary stop the schedule, and this was working great.

I'll try to collect some logs and screenshots over the weekend to provide more details about setup, versions, behaviour.

**Comment by bouwew** [comment]
@basvdl Schedule-off option was added in v0.45.0.
Also, a schedule not turning off / not being able to set `hvac_mode` to `heat` has been fixed as well.

**Comment by basvdl** [comment]
@bouwew Amazing! I'll make sure to spend some time to test this tomorrow. Thanks!!!

**Comment by basvdl** [comment]
@bouwew It works as designed ;), thank you!

I can use HA to disable and activate the schedule using the fire and calendar icon. When you activate the schedule again, it picks up the correct schedule (I have 5 zones and 5 schedules).

Disabling the schedule using the dropdown, setting it to off, also works!

Currently running:

HA: 2023.11.2
Plugwise-beta: 
```
  "requirements": ["plugwise==0.35.1"],
  "version": "0.45.0"
```

**Comment by bouwew** [comment]
@basvdl Thanks for testing and reporting :)

**Comment by bouwew** [comment]
@Torch1969 the requested feature was added in plugwise-beta v0.46.0

A gateway_mode Select was added, showing the options Normal, Pauze and Vacation.
