### ISSUE TITLE
[FEATURE]: Provide the 'heating on' information per Lisa thermostat entity, instead of shared across thermostats.

### ISSUE THREAD

**Issue by Getslow6** [plugwise/plugwise-beta#525]
### Describe the solution you are looking for

I have multiple Lisa's in my house and they share the same 'heating on' information:

![image](https://github.com/plugwise/plugwise-beta/assets/43093176/233e77dd-75b6-4d76-a878-ad2c50d945b7)

In the screenshot above you see the graphs of two Lisa's. They share the same 'heating on' information (the orange part), whilst only one of the two is requesting heat from the boiler. 

If it is possible to extract this information, it would be nice to see which Lisa is requesting heat similar to the Plugwise app:

![12](https://github.com/plugwise/plugwise-beta/assets/43093176/924191f7-7670-4be0-92aa-d3e71a2e2c1f)

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

Home Assistant Core

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor)

### What firmware version is your Plugwise product at?

Firmware: 3.7.8

### Your setup

I've copied my config below:

[config_entry-plugwise-f04c7fb7173ab830c05b644d377386b4.json.txt](https://github.com/plugwise/plugwise-beta/files/13363056/config_entry-plugwise-f04c7fb7173ab830c05b644d377386b4.json.txt)

3 Lisa's, multiple plugs, 3 Tom's, Adam.

### Additional context

Solution suggestion:

- The app shows an orange circle around the thermostat requesting heat (say `bThermostatRequestingHeat`)
- The app shows an orange flame when the boiler is on (say `bBoilerOn`)
- The orange area in the graph screenshot is the result the boiler turning on, while it is part of the climate entity.  (say the orange area is shown by `bThermostatHeatingOn `)
- I assume currently the 'heating on' is mapped to the boolean related to 'boiler on' (= orange flame in Plugwise app); `bThermostatHeatingOn = bBoilerOn`
- Possible solution would be: `bThermostatHeatingOn = bBoilerOn && bThermostatRequestingHeat`

**Comment by bouwew** [comment]
This is a known problem: https://github.com/home-assistant/core/issues/103386
Already fixed in pw-beta (https://github.com/plugwise/plugwise-beta/releases/tag/v0.44.2) but not yet in HA Plugwise.

**Comment by Getslow6** [comment]
Ok, missed that. Thanks for all the effort!
