### ISSUE TITLE
[FEATURE]: Add nice pictograms

### ISSUE THREAD

**Issue by Boemeltrein** [plugwise/plugwise-beta#526]
### Describe the solution you are looking for

Would be nice to have here nice pictograms in the same style as the other two,

Image: https://tweakers.net/i/KpPioriVkAPOhC9VZkotOWwdEEc=/x800/filters:strip_icc():strip_exif()/f/image/L7x3AdPHWdoCmuS8eTs2Qm0E.jpg?f=fotoalbum_large

### What type of installation are you running?

Home Assistant Core

### How did you install plugwise-beta?

Home Assistant Core

### What kind of Plugwise device is having issues?

Smile: Anna

### What firmware version is your Plugwise product at?

2023.11.2

### Your setup

Anna with 'stadsverwarming'

**Comment by bouwew** [comment]
Waiting for this to be implemented: https://github.com/home-assistant/architecture/discussions/980

Connected PR: https://github.com/home-assistant/core/pull/103294

**Comment by CoMPaTech** [comment]
[Developers blog was also updated](https://developers.home-assistant.io/blog/2024/01/19/icon-translations)

**Comment by bouwew** [comment]
Implemented via https://github.com/plugwise/plugwise-beta/pull/569

**Comment by bouwew** [comment]
This feature will be available in HA Core 2024.2.0 and plugwise-beta v0.47.1
