### ISSUE TITLE
ON/Off Valves change to % valves

### ISSUE THREAD

**Issue by djveldm** [plugwise/plugwise-beta#53]
**Is your feature request related to a problem? Please describe.**
I like to follow the "thinking/actions" of the Adam. For comments towards Plugwise Inc. it would be very nice to add the % valve states. It would be nice to have a graph for each zone with temperature Lisa, temperature water en valve state.
Your work up till now is impressive: I only started with Homeassistant last week and I am very happy with your Plugwise Beta!

**Describe the solution you'd like**
ON/State valves change to %.

**Describe alternatives you've considered**

**Home Assistant (please complete the following information):**
 - Version: 3.2
 - Deployment: raspberry/hassio
 - Installed plugwise version: plugwise-beta 0.20
 - Installed through HACS

**Smile (please complete the following information):**
 - Sort of Smile: Adam
 - Firmware: [check through the app or the integrations page in Home Assistant]
 - Setup: Adam. 3 Lisa's, 8 Toms Intergas Xtreem

**Additional context**

**Comment by bouwew** [comment]
Hi @djveldm, why do you want to use % for the valve-state? What does using % represent?
0% is closed, 100% is open? And 50% is half-open?

**Comment by djveldm** [comment]
Dear Bouwe,

 

The valves are changing its states in time. You can check that in the Plugwise app:

Hamburger/Indeling/Zone/Radiatorkraan: Ventielstand % (Adam firmware 3.0.20!, the previous firmware needs an extra click)

 

On/Off is for checking the system not enough.

 

Thank you for your swift reply!

 

Dirk

Amsterdam

 

 

Van: Bouwe Westerdijk [mailto:notifications@github.com] 
Verzonden: woensdag 29 april 2020 18:10
Aan: plugwise/plugwise-beta <plugwise-beta@noreply.github.com>
CC: djveldm <d.j.veldman@xs4all.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [plugwise/plugwise-beta] ON/Off Valves change to % valves (#53)

 

Hi @djveldm <https://github.com/djveldm> , why do you want to use % for the valve-state? What does using % represent?
0% is closed, 100% is open? And 50% is half-open?

**Comment by bouwew** [comment]
Actually, I had the same idea as you when I implemented this valve-position sensor.
Unfortunately, only two states are shown: 0% and 100%. Nothing in between, I specifically checked this by looking at the raw data (only showing 0.0 and 1.0) available from my Adam.
Because of this I chose to create a binary_sensor which shows "open" and "closed". The result is very clear, no question what 0% and 100% means.

**Comment by djveldm** [comment]
Do you have a line with Plugwise to ask?

 

Van: Bouwe Westerdijk [mailto:notifications@github.com] 
Verzonden: woensdag 29 april 2020 18:41
Aan: plugwise/plugwise-beta <plugwise-beta@noreply.github.com>
CC: djveldm <d.j.veldman@xs4all.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [plugwise/plugwise-beta] ON/Off Valves change to % valves (#53)

 

Actually, I had the same idea as you when I implemented this valve-position sensor.
Unfortunately, only two states are shown: 0% and 100%. Nothing in between, I specifically checked this by looking at the raw data (only showing 0.0 and 1.0) available from my Adam.
Because of this I chose to create a binary_sensor which shows "open" and "closed". The result is very clear, no question what 0% and 100% means.

**Comment by bouwew** [comment]
Yes I have a line with Plugwise. What do you want me to ask to Plugwise?

**Comment by bouwew** [comment]
@djveldm 
Tom and me have decided to not implement the requested change, as we do not see it as an enhancement.

But, we will point you to another solution: you can create your own %-sensor by creating a template sensor: https://www.home-assistant.io/integrations/template/
You can use this method to translate the value of the binary_sensor to a %-value.

**Comment by CoMPaTech** [comment]
Do note that if the valves would do %'s we can always change it accordingly but as it stands with 0% and 100% there would be no benefit of showing it as a % or through lovelace as a gauge.

**Comment by djveldm** [comment]
Thank you for this information.

I will try to implement  this suggestion, maybe it will work.

Greetings,

 

Dirk

 

Van: Bouwe Westerdijk [mailto:notifications@github.com] 
Verzonden: donderdag 30 april 2020 08:32
Aan: plugwise/plugwise-beta <plugwise-beta@noreply.github.com>
CC: djveldm <d.j.veldman@xs4all.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [plugwise/plugwise-beta] ON/Off Valves change to % valves (#53)

 

@djveldm <https://github.com/djveldm> 
Tom and me have decided to not implement the requested change, as we do not see it as an enhancement.

But, we will point you to another solution: you can create your own %-sensor by creating a template sensor: https://www.home-assistant.io/integrations/template/
You can use this method to translate the value of the binary_sensor to a %-value.

**Comment by djveldm** [comment]
The valves give % in the app of Plugwise. That’s why I wondered if it was possible to implement in Plugwise-Beta.

 

Greetings and thanks for your nice work, Dirk

 

Van: Tom [mailto:notifications@github.com] 
Verzonden: donderdag 30 april 2020 11:47
Aan: plugwise/plugwise-beta <plugwise-beta@noreply.github.com>
CC: djveldm <d.j.veldman@xs4all.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [plugwise/plugwise-beta] ON/Off Valves change to % valves (#53)

 

Do note that if the valves would do %'s we can always change it accordingly but as it stands with 0% and 100% there would be no benefit of showing it as a % or through lovelace as a gauge.

**Comment by CoMPaTech** [comment]
Just 2b clear: do that give "a value ending in %" or do they have values other than 0% and 100%?

If the app shows either "0%" or "100%" than it's just a matter of rewriting the current binary state. If they really do offer 20%, 50% et such, we'd be keen to know your Adams firmware and probably at least a snippet of the XML (http://w.x.y.z/core/domain_objects - look for something like the line indicate in [this output ](https://github.com/plugwise/Plugwise-Smile/blob/e2b8691262e7f361933c652c80d49f60c4853309/tests/adam_zone_per_device/core.domain_objects.xml#L147) shows)

**Comment by djveldm** [comment]
Adam software is 3.0.20 maar ook de vorige software gaf het % van de ventielstand aan. Zie de bijlages.
Deze zijn niet op het zelfde moment. Bij de dump stond het ventiel in de woonkamer 51%. valve_position 2020-04-30T13:24:09.579+02:00 0.51 2020-04-30T11:03:27.605+02:00
Begane grond toen 100% open valve_position 2020-04-30T13:14:15.409+02:00 1.00 2020-04-30T13:18:16.084+02:00
Derde verdieping: dicht valve_position 2020-04-13T12:59:45.338+02:00 0.00 2020-04-21T10:06:59.375+02:00

Het lijkt mij dat deze waarden zijn af te lezen.

Hartelijke groet,

Dirk


Van: Tom [mailto:notifications@github.com] 
Verzonden: donderdag 30 april 2020 12:59
Aan: plugwise/plugwise-beta <plugwise-beta@noreply.github.com>
CC: djveldm <d.j.veldman@xs4all.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [plugwise/plugwise-beta] ON/Off Valves change to % valves (#53)

Just 2b clear: do that give "a value ending in %" or do they have values other than 0% and 100%?
If the app shows either "0%" or "100%" than it's just a matter of rewriting the current binary state. If they really do offer 20%, 50% et such, we'd be keen to know your Adams firmware and probably at least a snippet of the XML (http://w.x.y.z/core/domain_objects - look for something like the line indicate in this output shows)

**Comment by bouwew** [comment]
Heb jij een Tom of een Floor?

Ik heb een Tom, en ik heb gisteren de verwarming even aan gezet om te kijken wat er in de Plugwise App gebeurt (dwz, niet in de app maar in de browser). Ik zag alleen maar 2 toestanden: 0%(closed) en 100%(open), niks ertussen. Ook firmware 3.0.20.

Die 51%, is die waarde constant? Of verandert deze waarde binnen een aantal seconden naar 0 of 100%?

En, sorry, ik zie geen bijlages? Ik denk niet dat github bijlages via email-beantwoorden ondersteund. Beter on dan direct een berichtje in het issue-topic te posten.

**Comment by djveldm** [comment]
Ik heb 8 Toms in drie verschillende zones. Per zone veranderen die Toms steeds synchroon. De waarden veranderen steeds. De 51% was dus een moment opname, het screenbeeld was iets daarvoor met andere waarde.
![firefox_2020-04-30_13-17-04](https://user-images.githubusercontent.com/63648032/80709725-0e00bb80-8aee-11ea-8c9f-5a0d1a607589.jpg)
[Plugwise dump.docx](https://github.com/plugwise/plugwise-beta/files/4558208/Plugwise.dump.docx)

**Comment by CoMPaTech** [comment]
Fijn al die verschillen - zelfs een Tom is dus geen Tom :(

**Comment by bouwew** [comment]
Ik zie dat jouw Tom adapter-gevoed wordt, misschien heeft dat er wat mee te maken: dat de klep dan langzamer open/dicht gaat? En juist sneller bij batterij-voeding zoals bij mij, om batterijen te sparen?

Aan de andere kant, zolang de standen anders dan 0% en 100% geen stationaire waarden zijn, wat voegt het zien van deze percentages toe? Leuk om te hebben maar na een tijdje kijk je er niet meer naar, je kijkt alleen naar de grote lijnen door de overvloed van informatie die HA je biedt. Ik spreek uit ervaring :)

**Comment by bouwew** [comment]
Hmm, na even nadenken, wanneer het percentage inderdaad niet alleen de waardes 0 en 100% aanneemt, dan werkt de binary_sensor niet goed. We kunnen relatief makkelijk een extra sensor naast de binary_sensor creëren, dan kun je kiezen.

**Comment by bouwew** [comment]
Wacht nog maar even, ik doe zo een release de deur uit, met de gevraagde sensor.

**Comment by bouwew** [comment]
Ok, versie 0.2.2 is gereleased.
Laat even weten of de sensor doet wat ie moet doen.
Je kunt de binary_sensors uitzetten wanneer je deze niet wilt zien.

**Comment by bouwew** [comment]
Sorry, de sensor-waarde geeft nu nog 0 en 1% als min en max.
Een fix komt eraan.

**Comment by bouwew** [comment]
V0.2.3 staat klaar.

**Comment by djveldm** [comment]
Super!
![firefox_2020-05-01_06-52-04](https://user-images.githubusercontent.com/63648032/80782989-91ff8580-8b78-11ea-9cfe-d0c6febf9931.jpg)

**Comment by CoMPaTech** [comment]
Nice!

**Comment by bouwew** [comment]
Thanks for letting us know the result!

**Comment by bouwew** [comment]
@djveldm 
Mijn Tom doet het dus ook:
![image](https://user-images.githubusercontent.com/11290930/80858769-c13af300-8c5b-11ea-9ddb-06df63bace30.png)

:)

**Comment by djveldm** [comment]
Bij mij lijkt het of de veranderingen van de klepposities niet doorkomen. Ik houd de waarde als bij de restart  van  Homeassistant.

Andere waarden van Plugwise Beta veranderen wel.

Ik weet (nog) niet hoe ik zo een mooie grafiek kan maken.

 

 

 

Van: Bouwe Westerdijk [mailto:notifications@github.com] 
Verzonden: zaterdag 2 mei 2020 10:01
Aan: plugwise/plugwise-beta <plugwise-beta@noreply.github.com>
CC: djveldm <d.j.veldman@xs4all.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [plugwise/plugwise-beta] ON/Off Valves change to % valves (#53)

 

@djveldm <https://github.com/djveldm> 
Mijn Tom doet het dus ook:
 <https://user-images.githubusercontent.com/11290930/80858769-c13af300-8c5b-11ea-9ddb-06df63bace30.png> 

:)

**Comment by bouwew** [comment]
Zo'n grafiek, dat zit standaard in HA. Ik denk gewoon op de pie-chart van de sensor klikken.
