### ISSUE TITLE
[BUG]:  ANNA ADAM still heats up while regulation is off

### ISSUE THREAD

**Issue by malosaa** [plugwise/plugwise-beta#531]
### Describe the bug.

Hi @bouwew 

I found an issue with Anna/Adam.
Well now using the heater again the regulation mode doesn't turn off @ adam.
Even when the regulation mode is turned off (show in home assistant) and Anna see the temperature is below the setpoint it still powers on my gas heater
Before when the regulation mode @ adam is turned off it doesn't heat up.

I did try this:
* set Anna from heat to off
* set Adam regulation mode to off 

What does work for now as a work around:
* Set the setpoint to 10c 

What could be the problem, not sure if its on my end:
ADAM Interface
![image](https://github.com/plugwise/plugwise-beta/assets/13116501/0af13b27-12f7-45b3-a709-030835a418fc)

ANNA Interface
![image](https://github.com/plugwise/plugwise-beta/assets/13116501/6a32d833-b3c5-4f24-b98e-d93a498ea640)

HASS:
![image](https://github.com/plugwise/plugwise-beta/assets/13116501/24f02525-7818-4eb3-87f2-afb60aa227b2)

DIAGNOSTIC
![image](https://github.com/plugwise/plugwise-beta/assets/13116501/c41c7184-94b1-4250-b540-8ff9f7d0d1f9)

ADAM PAGE Interface while setting setpoint higher and regulation mode off
![image](https://github.com/plugwise/plugwise-beta/assets/13116501/8a74e0c5-0484-48e1-b93d-bb78202f4c89)

Regards

### What version of Plugwise Beta are you using?

0.45.0

### What version of Home Assistant Core are you using?

2023.11.3

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor)

### What firmware version is your Plugwise product at?

3.7.8

**Comment by bouwew** [comment]
Hi Hector, please remind me, how does your heating-system look like?
Is the Anna connected to the Adam? Or is the Anna connected to a separate heating-system?

**Comment by malosaa** [comment]
Hi,

the Anna is connected to the Adam.
And Adam is connected to my heating-system

**Comment by bouwew** [comment]
Ok clear thanks.

Do you have a separate Plugwise integrations for the Anna and for the Adam?
If that is true, I would strongly suggest that you remove the Anna integration. You should not perform any control via the Anna-integration when there is an Adam-integration too. I mean, the Adam is the heating-system controller and the Anna should be considered as a wired Lisa.

The same is true for the Plugwise App: don't perform any changes in the Plugwise App for Anna unless it has effect for the Anna only like the temperature offset. 

When you follow these rules, do you still see the problem?

**Comment by bouwew** [comment]
I'll test this with my system when I'm home tonight.

**Comment by malosaa** [comment]
Like i see now i only have Adam 
![image](https://github.com/plugwise/plugwise-beta/assets/13116501/e9152e1c-6432-46c0-b6c4-5848b97011ae)

the devices:
![image](https://github.com/plugwise/plugwise-beta/assets/13116501/66024a08-8a3a-4b2e-9386-04dae2d040ed)

**Comment by bouwew** [comment]
This is what I like to see :)
The Adam is the gateway, connected to it are the Anna thermostat and the OpenTherm heating-system.

I will test tonight at home, I will look at the settings of my Anna too.

**Comment by malosaa** [comment]
Hi Bouwe,

Well i did try many other things, but sadly i can't stop it to heat.
The reason is i have for the day electric heating, and for the evening gas.
But when my specific m³ has been reached it should turn off the Anna/Adam, but it did not do it.

So what i did is modify my blueprint to set it at a lower temperature (19.5) and that works for now.

But its just weird, as in the summer for example when its hot the Anna goes in cooling mode and sets my thermostat on 40c (as i have no cooler but the regulation mode turned off) it won't start the heater in the summer.

So what i'm thinking does it something have to do with the add-on version?
I did not modify Anna or Adam in the settings at all, but did a software update of Anna or Adam got released this summer ? for me its on auto update, maybe that caused an issue.. i don't know.

regards

**Comment by bouwew** [comment]
I haven't had much time yet to look into the details.

I did see that my Anna does not have the Mode-option that is shown in your post above.
My Anna is at firmware 4.4.1

**Comment by malosaa** [comment]
Aah i see, i posted 2x same screenshot.
My anna is at 4.4.1 

![image](https://github.com/plugwise/plugwise-beta/assets/13116501/67f15690-0155-4dc2-8541-2a4936d46191)

![image](https://github.com/plugwise/plugwise-beta/assets/13116501/28c1130e-ae29-4196-83fb-722658f0d53d)

**Comment by malosaa** [comment]
Hi bouwe, 

I know you are really busy so i gonna post today some debug, and try to find the issue,

ADAM shows regulation = off 
```
<actuator_functionalities>
<regulation_mode_control_functionality id="7dd2c3b964c049e7923cfdae2ccc6908">
<regulation_mode_control id="57451d0a44da47e7a3d00c760dae7649"/>
<updated_date>2023-12-02T09:58:56.737+01:00</updated_date>
<type>regulation_mode</type>
<mode>off</mode>
<allowed_modes>
<mode>bleeding_cold</mode>
<mode>heating</mode>
<mode>off</mode>
<mode>bleeding_hot</mode>
</allowed_modes>
</regulation_mode_control_functionality>
<gateway_mode_control_functionality id="eb04094ab6604536848c38318f924196">
<gateway_mode_control id="779316bd806e47e196441169ac9b4af8"/>
<updated_date/>
<type>gateway_mode</type>
<mode>full</mode>
<allowed_modes>
<mode>light</mode>
<mode>secure</mode>
<mode>away</mode>
<mode>full</mode>
<mode/>
<mode>vacation</mode>
<mode>setup</mode>
</allowed_modes>
```

**Comment by bouwew** [comment]
That is my thinking too: it's a problem in the Adam!

**Comment by malosaa** [comment]
Today i got a message back from Plugwise,

They checked and indeed the heater turned on while ADAM was off.
However he replied again back and said, it supposed to work like that, so i have to turn down the temperature.

I'm 1000% sure that's not the case, as always when i turned off the regulation mode it did not turn at at all.. 
Whats the point ?

Or am i wrong in this one?

Can you confirm that too?

**Comment by malosaa** [comment]
He mailed back again, its not possible to turn off the heater.
What i did before.
So what happens now is when u turn off the regulation mode of Adam, Anna will request the heat directly, so no way to turn it off.

Regards

**Comment by bouwew** [comment]
As this is not related to the Plugwise integration / custom_component, let's close this issue.
