### ISSUE TITLE
HVAC action 'idle' is missing after updated from 0.1.18-1

### ISSUE THREAD

**Issue by WilbertVerhoeff** [plugwise/plugwise-beta#57]
**Describe the bug**
Plugwise beta custom component version 0.2.3
Legacy Anna user version 1.8.20
Home Assistant on a ubuntu server
installed true HACS

for the legacy Anna, after the update from 0.1.18-1 to higher the 'idle' action is missing in the thermostat. the thermostat remains in 'heating' mode. What i also noticed was that the most entities where duplicated and the domestic_hot_water and the heating_state is now gone.

Are those entities gone because it is not possible to get the data out of de legacy Anna?

I have copied the logfiles:
https://pastebin.com/wBpsPBBc

**Comment by bouwew** [comment]
Hi Wilbert,

There were were several  changes moving to version 0.2.0. Did your read the release notes?
Probably not :)
Please have a look here: https://github.com/plugwise/plugwise-beta/releases
Scroll down for the 0.2.0 release-notes.

The water_heater is gone and has been replaced by a sensor, this sensor is only present in systems with 2 or more thermostats, so when there is an Adam.
Domestic_hot_water-state is now shown via a binary_sensor. But not present with a legacy Anna as it does not provide the dhw_state in the XML-data.

Regarding the reported issue, I see `'heating_state': True` in your output. This causes the hvac_mode to show heating.
You can help us by capturing the /core/appliances XML-data for the situation that heating is off and for the situation that heating is on. From this data we can hopefully see what is going on.

**Comment by bouwew** [comment]
Also, IMPORTANT, please first uninstall and install plugwise-beta as shown in the 0.2.0 release notes.

**Comment by WilbertVerhoeff** [comment]
I am very sorry to not read the correct release notes. really a shame. I did't scroll down that much or as the dutch say: i was not looking further than my nose is long. I will send you the data as soon as possible.

Thank you for your reply.

**Comment by bouwew** [comment]
@WilbertVerhoeff can you edit custom_component files in your HA system?

**Comment by WilbertVerhoeff** [comment]
I think so. I want to take a look at it tomorrow.

**Comment by bouwew** [comment]
When easier, I can make a prerelease, which you can update to via HACS. Just takes a few minutes.
Let me know what you prefer

**Comment by WilbertVerhoeff** [comment]
It does not matter to me.  What works best for you.

**Comment by bouwew** [comment]
@WilbertVerhoeff , I've made a prerelease available: v0.2.4rc0
You can make this version visible in HACS, when you are in the selected Plugwise-beta integration, by clicking the 3 dots on the right and selecting "Show beta".

Please perform some tests and letus know the outcome here.

**Comment by WilbertVerhoeff** [comment]
@bouwew i did install the beta with the following results: 
when heating up the house it shows the correct state 'heating'. 
When turn off the heat it goes back to 'idle'. 
The hot water state shows 'on' when tapping hot water but only if i'm not heating the house. 

I have now captured the data when heating is on and when tapping hot water. I will send this to you and will look at it myself.

**Comment by bouwew** [comment]
Ok, thanks for testing! I'll take a look later, when I'm back at home.

**Comment by bouwew** [comment]
@WilbertVerhoeff version 0.2.4rc1 is available on HACS, please test.

**Comment by WilbertVerhoeff** [comment]
@bouwew i have tested the beta and it still gives the same result as the first one. It feels very responsive though. I think, looking at the data, this is as close as you can get with the data from the legacy anna.

Thank you for the quick response and the hard work!! If i can do more testing or data checks, please let me know.

**Comment by bouwew** [comment]
@WilbertVerhoeff Ok, thanks for testing!
But, what are you saying? When you are tapping hot water and heating at the same time, in the climate-entity `hvac_mode = heating` and `binary_sensor.auxiliary_dhw_state = off`?
And, on your Anna, both the heating- and the tapping-icons are shown?

**Comment by WilbertVerhoeff** [comment]
@bouwew exactly! On the physical thermostat the heating- and the tapping-icons are visible. But, on the web-interface only the flame icon is integrated. That one is responding to 'boiler_state'. So if you want to show on HA what is shown on the thermostat, then when the 'binary_sensor.auxiliary_dhw_state = on' so has to be 'hvac_mode = heating'. 

When you just turn on the heating, first thing it does is 'boiler_state = on'. So first the binary_sensor.auxiliary_dhw_state goes to 'on'. Next response (+- 10 sec) the 'intended_boiler_state = on' so then the thermostat shows 'heating' and the binary_sensor.auxiliary_dhw_state goes to 'off'.

When the thermostat is asking to heat the room and you take a shower at the same time, then 'hvac_mode = heating' and 'binary_sensor.auxiliary_dhw_state = off'. The physical thermostat then shows the flame and tapping icon. The thermostat in the web-interface only shows the flame. Inspecting the web-interface, it even has no tapping icon. So it never will be shown there.

**Comment by bouwew** [comment]
@WilbertVerhoeff 

First, "the thermostat in the web-interface only shows the flame", that is actually not relevant.
Which icons do you see in the web-interface, the Climate-Card? A calendar-icon and a flame-icon? If yes, the flame-icon means nothing more than "no-schedule" active. The flame-icon will be always on, also when the heating is off.

Second, based on what you are describing, the present solution is not really working :(
I did not know there was a delay between `boiler_state` and `intended_boiler_state`. On the other hand, that makes sense as there is also an `intended_thermostat_temperature` parameter that is "following" the `thermostat_temperature` setting. 
`intended_boiler_state` then means that the heater has really started to heat, if would think.

**Comment by bouwew** [comment]
Do you have the key `open_therm_oem_diagnostics_code` in your /core/appliances?

**Comment by bouwew** [comment]
Is it possible for you to monitor the timing of the `open_therm_oem_diagnostic_code` in your /core/appliances? Would its value changing be a better indicator of the heating and dhw_status?

Hmm, maybe I should ask Plugwise directly...
If they are willing to help.

**Comment by WilbertVerhoeff** [comment]
@bouwew i'n not talking about the HA climate card. That one is clear for me.

It is relevant what the Anna Web-interface shows as it listen to the data we are talking about. this tells that there is no data about the hot water state other then via the physical thermostat, that one on the wall. I will test the OEM code again and will share that with you.

For now i think that 'boiler_state on' should set the HVAC action to 'heating'. If we find a solution for the hot water, the HVAC action is also heating when tapping the water.

intended_boiler_temperature gives the temperature it wants for heating the house. As close as the temperature is getting to the set_ temperature, the lower intended_boiler_temperature will get to safe gas and not heating the house more then you set the temperature. intended_boiler_state says nothing more then: i have a intended_boiler_temperature you have to work with.

When tapping hot water, the burner will burn as hard as the flow of the hot water, so there is no intended_boiler_temperature to work with. It is a big question for me why  'intended_boiler_state' stays 'on' while it is not listening to the 'intended_boiler_temperature' at that time.

**Comment by bouwew** [comment]
Ah, you mean the Plugwise web-interface, sorry, I did not get that :)
And that web-interface does not show a tapping-icon?

Anyway, I've sent a question about this topic to Plugwise, Let's see what comes back.

**Comment by WilbertVerhoeff** [comment]
exactly. No tapping icon there. It even is not programed, it can never be there unless plugwise is changing that.

As I said: for now (and I think forever) the 'boiler_state' has to tell HA if HVAC action is 'idle' or 'heating'. And I hope we can get the dhw to work in the future. Maybe I'm giving myself to much of a headache in trying something to solve what is not possible with the current setup of the legacy Anna.

**Comment by bouwew** [comment]
I'm looking at your XML-files again. Better to look at the domain_object files is my present conclusion, appliances is showing boiler_state off while it is on in domain_objects..

**Comment by bouwew** [comment]
Quick summary when looking at domain_objects:

OEM code:
200  H, boiler_state = on
201  DHW or H+DHW, boiler_state = on
203 Off, boiler_state = off

modulation_level = 0 for DHW, not equal to 0 for H+DHW.

**Comment by WilbertVerhoeff** [comment]
@bouwew It takes over 7.5 minutes to change the oem code from 203 to 200 when turning on the central heating system. From 200 i tapped water. In the 10+ minutes, nothing changed. I did try it again and then it changed from 200 to 204 in a minute. But when i stopped tapping water the oem code now remains 204. So i think the oem code is not something to work with.

I have tested realtime and to make it clear:

boiler_state 'on' = the flame = heating up the boiler (you use gas)
boiler_state 'off' = boiler is at temperature OR heating and DHW are 'off'
intended_boiler_state 'on' = central heating is active (heating up the house)

modulation_level was the other way around by me. when i was heating up the house it was 0. when i tapped water it changed in range of 10 to 20.

Can i test something else for you? please let me know

**Comment by bouwew** [comment]
@WilbertVerhoeff just to be sure: at which XML-data have you been looking to obtain the above result? 
/core/appliances or /core/domain_objects?

**Comment by WilbertVerhoeff** [comment]
@bouwew domain, appliances and direct. All at the same time constantly refreshing one after the other.

**Comment by WilbertVerhoeff** [comment]
Btw, The beta is very responsive. When I change the set temperature, the fiscal thermostat changed directly.

**Comment by bouwew** [comment]
Ok, thanks.
I had the impression from the data you sent earlier that appliances was updated later than domain_objects.

Yes, the beta has been made responsive, this has been bugging me for a long time. But fortunately I found a pointer in other HA-code that gave me the "Pling!: Idea!" moment :)

To summarize all our work: we are back at square one: we can use `boiler-state` to detect that the CV-ketel or similar is heating. But we cannot determine whether heating is active or DHW is active.
OEM-diag-code is not usable, modulation is not usable, `intended_boiler_state` might be useful but it is not clear to me how.

**Comment by WilbertVerhoeff** [comment]
I agree with you. I can not make much sense out of the difference the files give me everytime. Like there is no logic or something.

I'm glad the 'heating' 'idle' thing is solved, and of course the response speed!

For me personally, I would like to have the intended_boiler_state info in HA to switch my floor heating pump. But I don't know if that is possible.

I want to thank you for the clear communication and the hard work!

**Comment by fsaris** [comment]
@WilbertVerhoeff your using the climate state idle now to stop the floor heating pump?

Ran into the same issue that with the use of this beta integration of plugwise Anna doesn't go into the `off` state anymore. 

If I understand your conversation correctly the `Off` state is now changed to `Idle`?

**Comment by fsaris** [comment]
`{{ states("climate.anna")}}` gives now only `heat` or `auto` when using stable version or `
0.2.4rc1`

In the legacy/core version it goes to state `off`

**Comment by WilbertVerhoeff** [comment]
@fsaris  Climate state is the 'HVAC action' so when the state is 'heating' it means that you are heating your home or tapping hot water. It is the same as the flame icon. Personally I now use the boiler_temperature to switch the pump on and off but it is not the right way. When the boiler temperature is below 25°C it turns off the pumps but its difficult every season.

**Comment by bouwew** [comment]
@fsaris indeed, `off` is gone. Also, don't use de state for this as the state is used to show the static mode the heating system is in: auto for controlled by a schedule or AI, heat for not controlled by a schedule or AI :) Nothing more, nothing less.
Instead, use the attribute hvac_action =  heating.

But, at the moment we are still testing, experimenting to find out how to properly show the heating- and dhw-states for the legacy Anna. The present implementation in 0.2.4rc1 is not correct.

**Comment by fsaris** [comment]
@bouwew  @WilbertVerhoeff Tnx for the clarification. Will test a little with the `available_schemas` value.

@WilbertVerhoeff my automation was currently based on the boiler flame with a delay before it turns of again. So if the boiler starts burning the pump also starts. And if it goes off/idle the pump will run for x minutes and (if the boiler didn't start heating again) then it will stop. 


Side question: I see `available_schemas` in the climate attributes. But not the active schema. Is that also something that could be added?

**Comment by WilbertVerhoeff** [comment]
@fsaris i am not a/the programmer, I just test and looking at the files. I will look into the files for you, but it is up to @bouwew if it is possible to add that function.

**Comment by fsaris** [comment]
Ah my mistake it's already there `selected_schema` but only in `auto` mode

**Comment by bouwew** [comment]
@fsaris Correct. Auto means a schema is selected. State = Heat means that no schema is selected, so selected_schema is not shown (something that HA does by itself).

**Comment by fsaris** [comment]
But what's strange it only gives 1 scheme as available scheme. But I have more of them defined

**Comment by bouwew** [comment]
What hardware do you have (name + firmware version)?

**Comment by fsaris** [comment]
I have a Anna

```
Extensie firmware
2018-02-08T11:15:57+01:00
Extensie hardware
6539-1301-2304
Display firmware
2018-02-08T11:15:53+01:00
Display hardware
6539-1301-500
```

Software: 4.0.15

**Comment by bouwew** [comment]
Ok, thanks.
Yes, there can be more than 1 schema for your Anna. Please make an Issue for this.
Then we will look into it.

**Comment by bouwew** [comment]
@CoMPaTech has the same hardware, he can see both the schema's he has created.
Can you show us you climate-entity (screengrab)?
Also, what is the name of the schema that is not shown?

**Comment by fsaris** [comment]
See https://github.com/plugwise/plugwise-beta/issues/61

**Comment by fsaris** [comment]
@WilbertVerhoeff @bouwew shouldn't `<type>intended_central_heating_state</type>` tell us the central heating state independent if the boiler is currently heating tap water?

**Comment by WilbertVerhoeff** [comment]
@fsaris where do you see that type? I can not find it in my files.

**Comment by bouwew** [comment]
Please explain?
Also please note you have a newer Anna, Wilbert has a legacy Anna, with different keys in his XML-data.

**Comment by fsaris** [comment]
Sorry didn't know he has the legacy version. I found this in `core/domain_objects`

Would be great if we could get this as binary sensor in homeassistent :smiley:

**Comment by bouwew** [comment]
At the moment central_heating_state is used to show the heating_state, and domestic_hot_water_state is used to show the tapping of hot water.
It's my idea that central_heating_state represents the heating demand signal from the thermostat, intended_central_heating_state represents the state of the pump in e.g. the CV-ketel.

**Comment by bouwew** [comment]
The binary_sensor for hot water tapping is available in plugwise-beta (custom_component). We are in the process of getting the beta-code into HA Core, replacing the present Plugwise integration.

**Comment by fsaris** [comment]
> At the moment central_heating_state is used to show the heating_state, and domestic_hot_water_state is used to show the tapping of hot water.
> It's my idea that central_heating_state represents the heating demand signal from the thermostat, intended_central_heating_state represents the state of the pump in e.g. the CV-ketel.

Will keep an eye on these values, but currently it looks that `hvac_action` isn't in `idle` state when the heating is off and tap water is heated. 

The
`<type>intended_central_heating_state</type>` value is `off` then

**Comment by bouwew** [comment]
I have noticed the same. For a multi-thermostat scenario, as with the Adam, using the intended_c_h_state will indeed be the better choice. But for a single-thermostat scenario I'm not 100% sure.

If you are interested to see how it all works, take a look at the code in both repositories present in this github.

**Comment by bouwew** [comment]
https://github.com/plugwise/Plugwise-Smile/pull/62

**Comment by bouwew** [comment]
@WilbertVerhoeff 
> 
For me personally, I would like to have the intended_boiler_state info in HA to switch my floor heating pump.
> 
In case you missed this, for legacy Anna, the heating-state (hvac_action = heating) is now based on `intended_boiler_state`. I found out via another user that `boiler_state` is on/off when the flame is on/off.

**Comment by fsaris** [comment]
But for the floor heating pump that wouldn't matter. As you only want to know if the hvac is active. So even if currently the flame is heating the tap water you want to know if you/system has the intention to heat the floor. And the `intended_boiler_state` is telling you exact that.

**Comment by bouwew** [comment]
Closed as @WilbertVerhoeff 's legacy Anna firmware has been updated to v3.1.11.
