### ISSUE TITLE
[BUG]: Modulation lvl of Adam not updated

### ISSUE THREAD

**Issue by malosaa** [plugwise/plugwise-beta#583]
### Describe the bug.

Well after weeks locked out of github i'm back.

I'm not sure if its a bug, but ask it anyway
At the plugin and looked under opentherm the modulation is showing 0 all the time, is that correct or does adam not support it ?
As i'm using Anna/Adam together .

Here the screen, 

![image](https://github.com/plugwise/plugwise-beta/assets/13116501/fa13efa2-f4a7-447a-8c8b-652c5a330aff)

Regards

### What version of Plugwise Beta are you using?

v0.46.2

### What version of Home Assistant Core are you using?

2024.2.1

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor)

### What firmware version is your Plugwise product at?

2.30

**Comment by bouwew** [comment]
I think it depends on the type of heater, my system, also Adam plus Anna, does not show the modulation.
I've seen it work in systems of other users. Didn't you ask this question before?

Anyway, please update to the latest version, v0.47.4. I've done a large update in the backend.
No real changes for legacy devices (your and mine P1) but for the Adam, less data is collected, only data from /core/domain_objects. Should half the data-traffic :)

**Comment by malosaa** [comment]
Ok thanks for the reply, i will update it and report back.
No i did not ask this before, maybe an other user.

Regards

**Comment by malosaa** [comment]
I did update, and no change for that specific entity, but i found out something about it.

I did found this:
```
<protocols>
<open_therm_boiler id="9aaXXXXXXXXXXXXXXXXXXXXXXX">
<open_therm_gateway id="7dXXXXXXXXXXXXXXXXXXXXXXX"/>
<open_therm_version>0.0</open_therm_version>
<is_modulating>true</is_modulating>
<maximum_capacity>24</maximum_capacity>
<minimum_modulation_level>25</minimum_modulation_level>
<with_cooling>false</with_cooling>
<with_domestic_hot_water>false</with_domestic_hot_water>
<with_domestic_hot_water_storage>false</with_domestic_hot_water_storage>
<with_master_low_off_and_pump_control>true</with_master_low_off_and_pump_control>
<with_secondary_heating_circuit>false</with_secondary_heating_circuit>
<smartgrid_control>smart_grid_off</smartgrid_control>
<test_mode>off</test_mode>
</open_therm_boiler>
</protocols>
````

however look the old log it did work 4 years ago, but did not change anything, so maybe an update of plugwise itself did mess it up

````
<point_log id="6b0XXXXXXXXXXXXXXXXXXXXXXX">
<type>maximum_modulation_level</type>
<unit/>
<updated_date>2020-05-06T17:00:32.519+02:00</updated_date>
<last_consecutive_log_date>2020-05-06T08:33:04.446+02:00</last_consecutive_log_date>
<interval/>
<modulation_level id="31eXXXXXXXXXXXXXXXXXXXXXXX"/>
<period start_date="2020-05-06T17:00:32.519+02:00" end_date="2020-05-06T17:00:32.519+02:00">
<measurement log_date="2020-05-06T17:00:32.519+02:00">1.00</measurement>
</period>
</point_log>
````

and here the now log showing 0 

```
<point_log id="896XXXXXXXXXXXXXXXXXXXXXXX">
<type>modulation_level</type>
<unit/>
<updated_date>2024-02-19T10:23:58.748+01:00</updated_date>
<last_consecutive_log_date>2024-01-13T23:20:18.821+01:00</last_consecutive_log_date>
<interval/>
<modulation_level id="181XXXXXXXXXXXXXXXXXXXXXXX"/>
<period start_date="2024-02-19T10:23:58.748+01:00" end_date="2024-02-19T10:23:58.748+01:00">
<measurement log_date="2024-02-19T10:23:58.748+01:00">0.00</measurement>
</period>
</point_log>
```

so i think we can close this, as its related to plugwise itself and not your integration 👍

**Comment by bouwew** [comment]
What do you see in the history of the modulation-sensor? Does is show always 0, also when the heating is active?
If yes then Plugwise probably stopped updating this parameter for you heating system.

**Comment by malosaa** [comment]
yes, it doesn't update.
So i think Plugwise itself does not support it anymore.

regards

**Comment by bouwew** [comment]
Ok thanks for reporting. I'll add `modulation` to the list of sensors that can go obsolete.

**Comment by bouwew** [comment]
Update, no I can't do that, it will break stuff.

**Comment by bouwew** [comment]
If you want to get rid of the entity, you can disable it in HA: toggle this switch of the modulation_level sensor to off:
![image](https://github.com/plugwise/plugwise-beta/assets/11290930/f8392463-69a8-4a3e-bb07-746133a534f5)

**Comment by malosaa** [comment]
@bouwew 

Thanks for the reply, its no problem, that entity is no problem for me, i don't care if it works or not:)

Thanks for the update and quick reply
