### ISSUE TITLE
[FEATURE]: Possibility to reboot Adam from Home Assistant

### ISSUE THREAD

**Issue by Getslow6** [plugwise/plugwise-beta#604]
### Describe the solution you are looking for

The web UI has the possibility to reboot the Adam gateway if you're connected to the local network. This is currently not possible in with the integration. 

### Is your feature request related to a problem? (optional)

While working on my house, sometimes I need to switch off an electricity group. When electricity comes back on the Adam Gateway sometimes isn't able to find the other Zigbee devices, which often can be resolved by rebooting the gateway. 

The only way to resolve this is by:
- physically pulling the power cable
- rebooting from the web interface (through a VPN or using a Firefox addon for example)

A button in Home Assistant to reboot the gateway would be nice, if this is possible!

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor)

### What firmware version is your Plugwise product at?

3.7.8

### Your setup

1x Adam
5x Tom
3x Lisa
3x Plugs

**Comment by bouwew** [comment]
@Getslow6
![image](https://github.com/plugwise/plugwise-beta/assets/11290930/6dd31d43-d0a7-4914-acd1-059bf7c90bb2)

You can test with version v0.51.0a0 if you like :)

**Comment by bouwew** [comment]
Implemented via #565, released in v0.51.0
