### ISSUE TITLE
[IDEAS/FUTURE/ROADMAP] Change polling time

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/plugwise-beta#68]
**Is your feature request related to a problem? Please describe.**
Not all users might benefit from power-sensors being polled every 10 seconds or climate users with every 60 seconds. Configurability is key in HA and so should our plugwise component.

**Describe the solution you'd like**
In the earlier releases we had a configurable timer, though that didn't diversify between power/climate. Polling power every 10 seconds sort of makes sense (it alignes with DSMR update timing) - climate every minute was reasonable middle ground, coming from overly polling old alphas - and it works fine once everything is up & running, but during early adoption users might feel differently.

**Describe alternatives you've considered**
Investigate if configuring after `config_flow` is feasible, if not verify if a `radio-button` (HTML) like structure is available so the user can choose various options. (To prevent absurd timings). Our earlier attempts (0.100-ish?) only had 'multiple-select' (HTML) like options.

If there is such an option, especially if you can 'unfold' something like 'advanced options' we might be able to support requests like #66

**Comment by bouwew** [comment]
A first attempt is available in the branch "config_options", it works in my system with a single Adam.
![image](https://user-images.githubusercontent.com/11290930/84685402-85719980-af3a-11ea-8557-f801162ba6df.png)

An "OPTIONS"-item has been added to the Integration-"icon", this function becomes available after the Integration has been added to Core.

**Comment by bouwew** [comment]
Solved by #85
