### ISSUE TITLE
[BUG]: Zigbee devices other than Aqara Smart Plug are not recognized

### ISSUE THREAD

**Issue by bouwew** [plugwise/plugwise-beta#768]
### Describe the bug.

As reported on Tweakers, https://gathering.tweakers.net/forum/list_message/80723140#80723140, a zigbee device connected to the Adam is not shown in HA.

### What version of Plugwise Beta are you using?

Core Plugwise

### What was the last working version of Plugwise Beta (or Core if not using beta before)?

None

### What version of Home Assistant Core are you using?

core-2024.11.0

### What type of installation are you running?

Home Assistant Supervised

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor)

### What firmware version is your Plugwise product at?

3.7.8

**Comment by VraagSander** [comment]
Hi, willing to help test.  Let me know what to do!

**Comment by bouwew** [comment]
OK very good. Do you have HACS installed?

**Comment by VraagSander** [comment]
Yes!
Verstuurd vanaf mijn iPhone

Op 24 nov 2024 om 07:37 heeft Bouwe Westerdijk ***@***.***> het volgende geschreven:

﻿

OK very good. Do you have HACS installed?

**Comment by bouwew** [comment]
OK clear.

The procedure then is:
- Delete the Plugwise integration from HA.
- Add the plugwise-beta repo in HACS, the repo is here: https://github.com/plugwise/plugwise-beta
- When added to HACS search for plugwise beta and click on it, the detailed repo info should appear. If not, restart HA and repeat searching for plugwise beta.
- Press the 3 vertical dots in the top right corner
- Press Redownload and select version v0.55.0a1, wait for the download to finish
- Restart HA
- Go to Settings --> Devices & Services, your Adam should be shown as discovered, shown as a button.
- Press that button, it will now use the Plugwise beta code to add the integration
- Enter the Smile ID of your Adam and press the ADD button(?)
- Next, look at the devices under the Adam, you should see several more representing you heating-zones.

Now, please test changing the temperature, preset, turn schedule to auto or heating, change to a different schedule.
Any issue, let me know :)

**Comment by bouwew** [comment]
About your finding 2, I've seen similar thing happen a few times before.
Forcing it to an active mode solved it in earlier cases as well. The problem never appeared after that, as far as I know :)

**Comment by bouwew** [comment]
Also FYI, the updates that are in pw-beta v0.55.0 also have been added to HA Core today.
I expect them to be released in HA 2024.12.0.

**Comment by VraagSander** [comment]
> @VraagSander OK thanks for your feedback. First, a question: which version are you running? The a1-version? If yes, please upgrade to v0.55.0 the latest released version. This version contains a few final improvements.

> Yes I was still running the a1 version. Upgraded today :) all still works well ;)




> Also FYI, the updates that are in pw-beta v0.55.0 also have been added to HA Core today. I expect them to be released in HA 2024.12.0.

That's awesome! good work !!!

**Comment by bouwew** [comment]
@VraagSander OK, that's good to know!
I'll probably need to account for that in the code.

**Comment by bouwew** [comment]
The solution for the original issue is part of the HA Core 2024.12.0 release.
