### ISSUE TITLE
more power information

### ISSUE THREAD

**Issue by willsmarthome** [plugwise/plugwise-beta#78]
Hi there,

First, thank you for stopping your time and creating this interface.
In an old version of my Plugwise Smile I also had the interval information.
psp1_interval_peak_produced_power
psp1_interval_off_peak_produced_power
psp1_interval_peak_consumed_power
psp1_interval_off_peak_consumed_power
Is it possible to add this to this version as well ??

Thanks!
Martin W.

**Comment by CoMPaTech** [comment]
Hi Martin,

It's a small world :) Hi again!

It should be possible to add these, let me check if there was any reason why it isn't added.

**Comment by willsmarthome** [comment]
Hi,

LoL, yes a small world.
Thanks!

**Comment by CoMPaTech** [comment]
Didn't forget about this one, just busy tidying up PR stuff for core - it's on my todolist still.

**Comment by CoMPaTech** [comment]
Hi Martin,

Version 0.2.16 should be available through HACS

**Comment by CoMPaTech** [comment]
Notes: added to 36406

**Comment by willsmarthome** [comment]
Thanks, looks great!

**Comment by CoMPaTech** [comment]
It's not in 111 yet - apparently beta and release are only for fixes, not sure it it will be in a .x release under 111, we'll see!

**Comment by CoMPaTech** [comment]
It's included in 0.112 released yesterday (but it has a rather hefty change/breaking log as a whole so read the announcement carefully)
