### ISSUE TITLE
Plugwise Stretch

### ISSUE THREAD

**Issue by willsmarthome** [plugwise/plugwise-beta#79]
Hi again, 
I also have a Plugwise Stretch.
With this Gateway you can operate the Plugwise Circle and Circle + and read the consumption. 

Are there also plans to add these?

**Comment by bouwew** [comment]
Please see here: https://community.home-assistant.io/t/plugwise-plugs-component/112246, end of the thread for latest info. @brefa is working on the custom_component and the integration in HA Core.

I have a Stick with a Circle and Stealth+, would work OK, unfortunately not fully with the latest version of the available custom_component. Not sure whether the Stretch is supported...

**Comment by bouwew** [comment]
Closing this as the requested enhancement is already being handled by someone else.

**Comment by bouwew** [comment]
@willsmarthome I googled the Stretch, it looks like an Adam, maybe a predecessor?. Which version do you have - 2.0/3.0? What is the firmware-version? Can you have a look at `http://your_stretch_ip/core/domain_objects`? If there is some XML-data to be seen, please capture the data and attach.

**Comment by willsmarthome** [comment]
@bouwew  
Version: 3.1.11

[Stretch30.zip](https://github.com/plugwise/plugwise-beta/files/4725387/Stretch30.zip)

Thank You!

**Comment by bouwew** [comment]
Interesting! Based on what's shown in this file I would like to receive a complete set of xml-files.

Can you please capture the xml-data from the following locations, when present:
- /core/appliances
- /core/locations
- /core/direct_objects
- /core/domain_object
- /core/modules

And send me the files, then I'll have a detailed look.

**Comment by willsmarthome** [comment]
[Stretch30xml.zip](https://github.com/plugwise/plugwise-beta/files/4725472/Stretch30xml.zip)

**Comment by bouwew** [comment]
On second thought, the Stretch contains the Stick I see now, so you can take out the Stick, plug it in your HA-server and use the Plugwise-stick custom_component I pointed out above to get what you want.
This will save me from doing double work :)

**Comment by willsmarthome** [comment]
OK,  thanks.
I will do that.

One question about the Anna.
Can I change the settings with a script like temperature and programm?
So I can change the settings with automation.

**Comment by bouwew** [comment]
Yes, the commands shown here: https://www.home-assistant.io/integrations/climate/
can be used, as far as they are available: climate.set_preset_mode, climate.set_temperature and climate.set_hvac_mode (only switch the schedule on / off, you cannot switch to another schedule).

**Comment by willsmarthome** [comment]
Thanks @bouwew !!

**Comment by willsmarthome** [comment]
Thanks @bouwew !!
