### ISSUE TITLE
climate.anna

### ISSUE THREAD

**Issue by willsmarthome** [plugwise/plugwise-beta#80]
Hi,

I have problems with my Anna interface.
Installing the Integration works OK.
When I whant to use the entity climate.anna it's reporting: "not responding"
This sensor works:
binary_sensor.auxiliary_dhw_state

I asume that the connectivity with the gateway is OK.

Anny ideas?

**Comment by CoMPaTech** [comment]
Are there any warnings or errors in the error log? url+`/developer-tools/logs`

**Comment by bouwew** [comment]
Also: 'When I whant to use the entity climate.anna it's reporting: "not responding"', what do you mean by 'want to use'? Do you want to change the temperature? Or anything else? And where do you see the message 'not responding'?

**Comment by willsmarthome** [comment]
Sorry,
@bouwew, when I want to install it in the GUI.

I have found these messages:
Error while setting up plugwise-beta platform for climate
2 juni 2020 21:41:47 – Klimaat (ERROR)
Error while setting up plugwise-beta platform for sensor
2 juni 2020 21:41:47 – Sensor (ERROR)
Unexpected error fetching Smile data:
12:18:02 – Plugwise Beta for Home Assistant (ERROR) - bericht kwam voor het eerst om 2 juni 2020 23:02:28 en verschijnt 11 malen
Error sending command to Plugwise: /core/domain_objects
12:18:02 – /usr/local/lib/python3.7/site-packages/Plugwise_Smile/Smile.py (ERROR) - bericht kwam voor het eerst om 2 juni 2020 23:32:29 en verschijnt 4 malen

**Comment by bouwew** [comment]
Not sure what is causing this. Did you remove the old plugwise custom_component files you were using, and the configuration-lines in configuration.yaml?
If yes, next, remove the Plugwise-beta integration via Instellingen --> Integraties --> Plugwise beta --> 3 dots --> Delete.
Next, restart HA.
Next, make sure HACS shows you have the latest version = 0.2.15.
Next, add the integration again via Instellingen --> Integraties --> +

**Comment by bouwew** [comment]
Do the integration for each Smile that you have there, you have 2 I think?

When the integration(s) is (are) done, there should be a (two) Plugwise-beta "block(s)" in the list of integrations. How many apparaten and entities  are shown for the Anna?

**Comment by willsmarthome** [comment]
No, i have also the old component installed.
I will remove first the old component and files.

![anna1](https://user-images.githubusercontent.com/65604497/83630041-70405680-a59b-11ea-8618-0aee6c02ca42.jpg)
![anna2](https://user-images.githubusercontent.com/65604497/83630043-70d8ed00-a59b-11ea-9e8a-cfb3ed89f194.jpg)
![anna2a](https://user-images.githubusercontent.com/65604497/83630044-70d8ed00-a59b-11ea-85d6-deac96cabeb9.jpg)
![anna3](https://user-images.githubusercontent.com/65604497/83630045-70d8ed00-a59b-11ea-879c-30ce75ead216.jpg)

First at work ;-)

**Comment by bouwew** [comment]
That's more like it!

All is working now?

**Comment by bouwew** [comment]
Sorry, not working fully, there should be quite some sensors too. Are these not there?
Please check the HA log for errors. When clicking on an error, there should pop up a window with more detailed information.

**Comment by willsmarthome** [comment]
I will first delete the old installation.
Sorry, but my "boss" keeps calling me.

I will give you a update later.

**Comment by willsmarthome** [comment]
Error setting up entry EWV Zolder for upnp
13:39:22 – components/upnp/device.py (ERROR) - bericht kwam voor het eerst om 13:39:06 en verschijnt 5 malen
Error doing job: Unclosed client session
13:39:16 – core.py (ERROR)
Startup Theme: Error executing script. Service not found for call_service at pos 2: Unable to find service device_tracker/guest_presence
13:39:07 – Automatisering (ERROR)
Error doing job: Task exception was never retrieved
13:39:06 – components/onvif/config_flow.py (ERROR)
Config entry for upnp not ready yet. Retrying in 5 seconds.
13:39:06 – config_entries.py (WARNING)
Error while setting up plugwise-beta platform for climate
13:39:01 – Klimaat (ERROR)
Error while setting up plugwise-beta platform for sensor
13:39:01 – Sensor (ERROR)

**Comment by willsmarthome** [comment]
I deleten all: Plugwise beta custom component, files, folders....
After a new installation Anna is still unavalible.
My logging:
Error setting up entry EWV Zolder for upnp
14:13:04 – components/upnp/device.py (ERROR) - bericht kwam voor het eerst om 14:12:48 en verschijnt 5 malen
Error doing job: Unclosed client session
14:12:59 – core.py (ERROR)
Config entry for upnp not ready yet. Retrying in 5 seconds.
14:12:48 – config_entries.py (WARNING) - bericht kwam voor het eerst om 14:12:48 en verschijnt 2 malen
Error while setting up plugwise-beta platform for climate
14:12:43 – Klimaat (ERROR)
Error while setting up plugwise-beta platform for sensor
14:12:43 – Sensor (ERROR)

**Comment by bouwew** [comment]
When you click on this error: 
Error while setting up plugwise-beta platform for climate
14:12:43 – Klimaat (ERROR)

What is shown in the window that pops up?

**Comment by willsmarthome** [comment]
Logger: homeassistant.components.climate
Source: custom_components/plugwise-beta/climate.py:237
Integration: Klimaat (documentation, issues)
First occurred: 14:12:43 (1 occurrences)
Last logged: 14:12:43

Error while setting up plugwise-beta platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 444, in _async_add_entity
    await entity.async_added_to_hass()
  File "/config/custom_components/plugwise-beta/__init__.py", line 203, in async_added_to_hass
    self._async_process_data()
  File "/config/custom_components/plugwise-beta/climate.py", line 237, in _async_process_data
    climate_data = self._api.get_device_data(self._dev_id)
  File "/usr/local/lib/python3.7/site-packages/Plugwise_Smile/Smile.py", line 661, in get_device_data
    details["location"]
  File "/usr/local/lib/python3.7/site-packages/Plugwise_Smile/Smile.py", line 970, in get_schemas
    moment_1, moment_2 = period.split(",")
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by bouwew** [comment]
Thanks, this helps!

Two questions:
- What is the firmware version of your Anna?
- Do you have a weekschedule defined in the Plugwise App/website? If yes, how many? If not, let me know as well.

**Comment by willsmarthome** [comment]
1. Version 4.0.19
2. Three schedules:
      - Alternatief
      - Standaard
      - Uit Huis

**Comment by bouwew** [comment]
An additional request: can you please capture the XML-data on the webpage http://your_smile_ip/core/domain_objects``? When looking at the page, right-click --> save as --> some_name.xml.

**Comment by bouwew** [comment]
Ah, v4.0.19, there must be a change in the xml-data that we don't know about.

**Comment by willsmarthome** [comment]
[Anna4019.zip](https://github.com/plugwise/plugwise-beta/files/4723632/Anna4019.zip)

**Comment by bouwew** [comment]
The "problem" is this:

One schedule is shown in the XML-data like this:
``` 
		<name>Uit Huis</name>
		<description></description>
		<template id="c89b5aba26d24542a71f3b544e32f2fa" tag="zone_preset_based_on_time_and_presence_with_override"/>
		<active>false</active>
		<created_date>2019-11-05T16:12:49.973+01:00</created_date>
		<modified_date>2020-04-22T21:40:05.077+02:00</modified_date>
		<deleted_date></deleted_date>
		<directives>
			<when time="mo 06:00"><then setpoint="21"/></when>
			<when time="mo 07:00"><then setpoint="16"/></when>
			<when time="mo 16:45"><then setpoint="21"/></when>
			<when time="mo 22:00"><then setpoint="16"/></when>
			<when time="tu 06:00"><then setpoint="21"/></when>
			<when time="tu 07:00"><then setpoint="16"/></when>
			<when time="tu 16:45"><then setpoint="21"/></when>
			<when time="tu 22:00"><then setpoint="16"/></when>
```

And another like this:
```
		<name>Alternatief</name>
		<description></description>
		<template id="c89b5aba26d24542a71f3b544e32f2fa" tag="zone_preset_based_on_time_and_presence_with_override"/>
		<active>true</active>
		<created_date>2020-03-17T20:31:53.152+01:00</created_date>
		<modified_date>2020-04-27T16:18:18.466+02:00</modified_date>
		<deleted_date></deleted_date>
		<directives>
			<when time="[mo 07:00,mo 08:30)"><then preset="home"/></when>
			<when time="[tu 07:00,tu 08:30)"><then preset="home"/></when>
			<when time="[we 07:00,we 08:30)"><then preset="home"/></when>
			<when time="[th 07:00,th 08:30)"><then preset="home"/></when>
			<when time="[fr 07:00,fr 08:30)"><then preset="home"/></when>
			<when time="[su 08:00,su 10:00)"><then preset="home"/></when>
			<when time="[sa 08:00,sa 10:00)"><then preset="home"/></when>
			<when time="[su 21:00,mo 07:00)"><then preset="asleep"/></when>
			<when time="[mo 21:00,tu 07:00)"><then preset="asleep"/></when>
			<when time="[tu 21:00,we 07:00)"><then preset="asleep"/></when>
```

Our code expects the format of the 2nd schedule, it does not recognize the code of the 1st shown schedule.

Can you complete remove the Uit Huis schedule and create a new one, from scratch? Maybe that will help.

**Comment by bouwew** [comment]
Please restart HA after you have recreated the schedule.
If the error is still present, please check the XML-data yourself, check to see if the format as shown in the post above is still the same.

**Comment by willsmarthome** [comment]
YES!!!!
Problem solved!!!
Thanks!!!!!

**Comment by bouwew** [comment]
Glad to hear that :)
