### ISSUE TITLE
Can a change the ip adres?[FEATURE]

### ISSUE THREAD

**Issue by willsmarthome** [plugwise/plugwise-beta#90]
Hello,

Is it possible to change de congifuration manual.
I want to change the ip adres of the Anna configuration.

**Comment by bouwew** [comment]
Hi Martin,

Sure, just delete the plugwise integration in HA, change the IP address of the Anna, then add the integration in HA again and enter the new IP address. That's all, no changes needed in the Plugwise code.

**Comment by willsmarthome** [comment]
OK
Solved!
See my bug report.
