### ISSUE TITLE
Installing more then one Integration[BUG]

### ISSUE THREAD

**Issue by willsmarthome** [plugwise/plugwise-beta#91]
![Aantekening 2020-07-07 100809](https://user-images.githubusercontent.com/65604497/86744355-d9ebce80-c039-11ea-9211-73424a0f87e9.jpg)
Good morning,

If I want to add a new one to an existing one via Integrations, I get an empty pop-up (see image) and then the selection pop-up again. It is not possible to add an Integration. When I remove and reinstall the full Integration, I can install one instance, eg the P1 or Anna, a second one fails. I hope the problem description is understandable.

Plugwise Smile custom_component (BETA): 0.3.2
HACS version: 1.1.3
HassOS 4.11
Home Assistant 0.112.3

**Comment by bouwew** [comment]
Can you edit code in the custom_component files?

**Comment by bouwew** [comment]
Also, can you show the details of the corresponding error show in HA Logs?

**Comment by willsmarthome** [comment]
> 
> 
> Can you edit code in the custom_component files?

Yes i can.

**Comment by willsmarthome** [comment]
> 
> 
> Also, can you please show the details of the corresponding error show in HA Logs?


See screensots:

![pwbeta errorlog](https://user-images.githubusercontent.com/65604497/86756829-f809fc80-c042-11ea-8fa1-1006622f04d3.jpg)

![pwbeta errorlog-1](https://user-images.githubusercontent.com/65604497/86757620-90a07c80-c043-11ea-975b-f6fe91dfc316.jpg)

**Comment by bouwew** [comment]
Thank, that's exactly what I was looking for.

Please comment out these lines in the file `config_flow.py`:
```
        for entry in self._async_current_entries():
            if entry.unique_id == self.discovery_info.get("hostname").split(".")[0]:
                self._abort_if_unique_id_configured()
```

Then restart HA Core and try to add both integrations once more and let us know the result.

**Comment by willsmarthome** [comment]
> 
> 
> Thanks, that's exactly what I was looking for.
> 
> Please comment out these lines in the file `config_flow.py`, in the function `async def async_step_user`:
> 
> ```
>         for entry in self._async_current_entries():
>             if entry.unique_id == self.discovery_info.get("hostname").split(".")[0]:
>                 self._abort_if_unique_id_configured()
> ```
> 
> Then restart HA Core and try to add both integrations once more and let us know the result.

YES!, it's working

**Comment by bouwew** [comment]
Thanks for testing and reporting back.
I will remove those lines of code from Plugwise-beta.

FYI, one more feature coming soon: showing Plugwise notifications in HA Core.

**Comment by willsmarthome** [comment]
> 
> 
> Thanks for testing and reporting back.
> I will remove those lines of code from Plugwise-beta.
> 
> FYI, one more feature coming soon: showing Plugwise notifications in HA Core.

Thank you for your solution.
"See" you soon. ;-)

**Comment by bouwew** [comment]
@willsmarthome Please test the new version v0.4.0. I wonder if you will get to see any Notifications?
I have Plugs so when I remove a Plug there will be a notification after some time. I also use a Plug to control my floor-heating pump, sometimes there's a message that the pump "has not run for 24hrs, it is running for a short time to prevent rust-forming".
